//! Lunar scene: host-side view setup for the generated lunar surface.
//!
//! The lunar map itself — terrain, nav grid, tileset, landing zones — is
//! generated by the ROM guest (`guest/lunar-guest`) and installed through the
//! bulk terrain SDK imports.  This module owns only the view setup that runs
//! after the guest installs the terrain and landing zones: camera framing and
//! the airless light preset.

use classic_core::components::Tilemap;
use classic_engine::Engine;

use crate::state::DemoStateRef;

/// Centre the camera on the first landing zone (uploaded by the guest).
pub fn focus_camera_on_spawn(engine: &mut Engine) {
    let Some(&(sx, sy)) = engine.spawn_points.first() else { return };
    let Some(tm_entity) = engine.entity_by_role(classic_core::RoleKind::Tilemap) else { return };
    let scale = engine
        .world
        .get::<&Tilemap>(tm_entity)
        .map(|tm| tm.scale)
        .unwrap_or(glam::Vec3::new(45.0, 45.0, 1.0));

    let iso = glam::Mat4::from_scale(scale) * classic_core::math::cartesian_to_iso_4().inverse();
    let origin = iso.transform_point3(glam::Vec3::new(sx as f32, sy as f32, 0.0));
    engine.camera.position.x = origin.x;
    engine.camera.position.y = origin.y;
}

/// Zoom out for the generated terrain, centre on the first spawn, and apply
/// the airless lunar light preset.
pub fn setup_view(engine: &mut Engine, state: &DemoStateRef) {
    // Zoom out: at scale 1.0 a 45px tile fills the view with ~28 tiles, which
    // shows none of the terrain the generator produces.
    engine.camera.scale = glam::Vec3::new(0.32, 0.32, 1.0);
    focus_camera_on_spawn(engine);
    // Airless lighting: near-zero ambient and a hard low sun, which is what
    // makes the crater relief legible.
    crate::lighting::apply_light_preset(engine, state, "lunar");
    // The editor grid overlay fights the natural surface.
    engine.show_grid = false;
}
