[package]
name = "classic-core"
version.workspace = true
edition.workspace = true

[dependencies]
classic-pathfinder = { path = "../classic-pathfinder" }
classic-terrain = { path = "../classic-terrain" }
glam.workspace = true
hecs.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
log.workspace = true
bytemuck.workspace = true

[dev-dependencies]
