[package]
name = "classic-demo"
version.workspace = true
edition.workspace = true

[dependencies]
classic-core = { path = "../classic-core" }
classic-gfx = { path = "../classic-gfx" }
classic-engine = { path = "../classic-engine" }
classic-rom = { path = "../classic-rom" }
classic-guest = { path = "../classic-guest" }

glam.workspace = true
glow.workspace = true
hecs.workspace = true
anyhow.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
