//! `xtask`: the Rust asset/ROM build tool for classic-wgl.
//!
//! Replaces the former Node toolchain (`copy-assets.mjs`, `build-guest.mjs`,
//! `build-roms.mjs`, `make-font-atlas.mjs`) with
//! `cargo xtask <assets|guests|roms|all>`.  ROMs are packed as zip archives via
//! `classic_rom::Rom::pack` from the `assets/` submodule + the per-scene
//! `roms/<scene>/` authoring sources into `roms/out/*.rom` (gitignored, embedded
//! by the apps via `include_bytes!`).  The SDF font atlas is generated by the
//! `crates/sdf-atlas` Rust crate.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::Context;
use classic_rom::{ResourceKind, ResourceSet, Rom, RomManifest};

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap().to_path_buf()
}

fn main() -> anyhow::Result<()> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let cmd = args.first().map(String::as_str).unwrap_or("all");
    let root = root();

    match cmd {
        "assets" => copy_assets(&root),
        "guests" => build_guests(&root),
        "roms" => pack_roms(&root),
        "lrvtest-map" => gen_lrvtest_map(&root),
        "all" => {
            copy_assets(&root)?;
            build_guests(&root)?;
            pack_roms(&root)
        }
        other => {
            anyhow::bail!("unknown command `{other}` (expected assets|guests|roms|lrvtest-map|all)")
        }
    }
}

/// Generate the hand-authored `lrvtest` ramp-course grids
/// (`roms/lrvtest/maps/{tiles,heights,nav}.json`).  A small deterministic test
/// track for visually tuning the wheeled-vehicle suspension/jump: a flat base
/// with a ramp rising in each of the eight directions, a central hill to launch
/// off, and a raised step (curb) to cross.
fn gen_lrvtest_map(root: &Path) -> anyhow::Result<()> {
    let size: usize = 48; // tiles per axis
    let n = size + 1; // vertices per axis (height grid)

    let tiles = vec![9u32; size * size];
    let nav = vec![1u32; size * size];

    let mut h = vec![1.0f32; n * n];
    let idx = |x: usize, y: usize| y * n + x;
    let rise = 3.0f32; // ramp top = base + rise
    let len = 8.0f32; // ramp run, in tiles

    // Central hill (crest to launch off): +2 peak at (24,24), radius 5.
    for y in 0..n {
        for x in 0..n {
            let dx = x as f32 - 24.0;
            let dy = y as f32 - 24.0;
            let d = (dx * dx + dy * dy).sqrt();
            if d < 5.0 {
                let bump = 2.0 * (1.0 - d / 5.0);
                h[idx(x, y)] = h[idx(x, y)].max(1.0 + bump);
            }
        }
    }

    // Cardinal ramps (rise along +x / -x / +y / -y).
    for y in 20..=29 {
        for x in 33..=41 {
            h[idx(x, y)] = h[idx(x, y)].max(1.0 + rise * (x - 33) as f32 / len);
        }
        for x in 7..=15 {
            h[idx(x, y)] = h[idx(x, y)].max(1.0 + rise * (15 - x) as f32 / len);
        }
    }
    for x in 20..=29 {
        for y in 33..=41 {
            h[idx(x, y)] = h[idx(x, y)].max(1.0 + rise * (y - 33) as f32 / len);
        }
        for y in 7..=15 {
            h[idx(x, y)] = h[idx(x, y)].max(1.0 + rise * (15 - y) as f32 / len);
        }
    }

    // Diagonal ramps (rise along the four diagonals).
    for x in 33..=41 {
        for y in 33..=41 {
            h[idx(x, y)] = h[idx(x, y)].max(1.0 + rise * ((x + y) as f32 - 66.0) / 16.0);
        }
        for y in 7..=15 {
            h[idx(x, y)] =
                h[idx(x, y)].max(1.0 + rise * (x as f32 + (15.0 - y as f32) - 40.0) / 16.0);
        }
    }
    for x in 7..=15 {
        for y in 7..=15 {
            h[idx(x, y)] = h[idx(x, y)].max(1.0 + rise * (30.0 - (x + y) as f32) / 16.0);
        }
        for y in 33..=41 {
            h[idx(x, y)] =
                h[idx(x, y)].max(1.0 + rise * (15.0 - x as f32 + y as f32 - 40.0) / 16.0);
        }
    }

    // Step (curb): a raised +1 plateau in the south band, east of the south ramp.
    for x in 20..=36 {
        for y in 42..=47 {
            h[idx(x, y)] = h[idx(x, y)].max(2.0);
        }
    }

    let out_dir = root.join("roms/lrvtest/maps");
    fs::create_dir_all(&out_dir)?;
    fs::write(out_dir.join("tiles.json"), serde_json::to_string(&tiles)?)?;
    fs::write(out_dir.join("nav.json"), serde_json::to_string(&nav)?)?;

    let heights: Vec<f32> = h.iter().map(|v| (v * 100.0).round() / 100.0).collect();
    fs::write(out_dir.join("heights.json"), serde_json::to_string(&heights)?)?;
    println!("wrote roms/lrvtest/maps/tiles.json, nav.json, heights.json ({}x{} grid)", size, size);
    Ok(())
}

/// Copy source game assets from the `assets/` submodule into `roms/out/res/`
/// and `roms/out/animations/`, then generate the SDF font atlas.
fn copy_assets(root: &Path) -> anyhow::Result<()> {
    let out_res = root.join("roms/out/res");
    let out_anims = root.join("roms/out/animations");
    fs::create_dir_all(&out_res)?;
    fs::create_dir_all(&out_anims)?;

    for entry in fs::read_dir(root.join("assets/demo"))? {
        let p = entry?.path();
        if p.extension().and_then(|e| e.to_str()) == Some("png") {
            let name = p.file_name().unwrap().to_os_string();
            fs::copy(&p, out_res.join(name))?;
        }
    }

    for entry in fs::read_dir(root.join("assets/buildings"))? {
        let dir = entry?.path();
        let sheet = dir.join("spritesheet.png");
        if sheet.is_file() {
            let name = format!("{}.png", dir.file_name().unwrap().to_string_lossy());
            fs::copy(&sheet, out_res.join(name))?;
        }
    }

    let rocket = root.join("assets/vehicles/us-rocket");
    for f in ["landing_spritesheet.png", "launch_spritesheet.png"] {
        let src = rocket.join(f);
        if src.is_file() {
            fs::copy(&src, out_res.join(f))?;
        }
    }
    for (src, dst) in
        [("landing_offsets.bin", "rocketLanding.bin"), ("launch_offsets.bin", "rocketLaunch.bin")]
    {
        let s = rocket.join(src);
        if s.is_file() {
            fs::copy(&s, out_anims.join(dst))?;
        }
    }

    // LRV rover: body + 4 wheel spritesheets (each 8 directions) + the vehicle
    // definition sidecar.
    let lrv = root.join("assets/vehicles/lrv");
    for (src, dst) in [
        ("lrv_body.png", "lrv_body.png"),
        ("lrv_wheel_fl.png", "lrv_wheel_fl.png"),
        ("lrv_wheel_fr.png", "lrv_wheel_fr.png"),
        ("lrv_wheel_rl.png", "lrv_wheel_rl.png"),
        ("lrv_wheel_rr.png", "lrv_wheel_rr.png"),
        ("lrv.json", "lrv.json"),
    ] {
        let s = lrv.join(src);
        if s.is_file() {
            fs::copy(&s, out_res.join(dst))?;
        }
    }

    // SDF font atlas (Rust `sdf-atlas` crate).
    let font_path = root.join("assets/fonts/DejaVuSans.ttf");
    let font_bytes =
        fs::read(&font_path).with_context(|| format!("read {}", font_path.display()))?;
    let atlas = sdf_atlas::generate(
        &font_bytes,
        &sdf_atlas::Options { family: "DejaVuSans".into(), ..Default::default() },
    )?;
    fs::write(out_res.join("dejavusans-sdf.png"), &atlas.png)?;
    fs::write(out_res.join("dejavusans-sdf.json"), &atlas.metrics_json)?;

    println!("copied assets to roms/out/");
    Ok(())
}

/// Compile the `guest/*` crates to wasm32 and stage them into `roms/out/code/`.
fn build_guests(root: &Path) -> anyhow::Result<()> {
    let out_code = root.join("roms/out/code");
    fs::create_dir_all(&out_code)?;
    let target = root.join("target");

    for (crate_name, out_name) in
        [("demo-guest", "demo.wasm"), ("lunar-guest", "lunar.wasm"), ("lrv-guest", "lrv.wasm")]
    {
        let manifest = root.join("guest").join(crate_name).join("Cargo.toml");
        let status = Command::new("cargo")
            .arg("build")
            .arg("--manifest-path")
            .arg(&manifest)
            .args(["--target", "wasm32-unknown-unknown", "--release"])
            .env("CARGO_TARGET_DIR", &target)
            .status()
            .with_context(|| format!("build guest {crate_name}"))?;
        if !status.success() {
            anyhow::bail!("guest build failed: {crate_name}");
        }
        let wasm = target
            .join("wasm32-unknown-unknown")
            .join("release")
            .join(format!("{}.wasm", crate_name.replace('-', "_")));
        fs::copy(&wasm, out_code.join(out_name))?;
        println!("staged roms/out/code/{out_name}");
    }
    Ok(())
}

/// A bundled binary grid resource (name, authoring JSON source, element type).
struct Grid {
    name: &'static str,
    source: &'static str,
    element: &'static str,
}

fn pack_roms(root: &Path) -> anyhow::Result<()> {
    pack_scene(
        root,
        "demo",
        "roms/demo/manifest.json",
        "roms/demo/state.json",
        "demo.wasm",
        &[
            Grid { name: "demo.tiles", source: "roms/demo/maps/tiles.json", element: "u32" },
            Grid { name: "demo.nav", source: "roms/demo/maps/nav.json", element: "u32" },
        ],
    )?;
    pack_scene(
        root,
        "lunar",
        "roms/lunar/manifest.json",
        "roms/lunar/state.json",
        "lunar.wasm",
        &[],
    )?;
    pack_scene(
        root,
        "lrvtest",
        "roms/lrvtest/manifest.json",
        "roms/lrvtest/state.json",
        "lrv.wasm",
        &[
            Grid { name: "lrvtest.tiles", source: "roms/lrvtest/maps/tiles.json", element: "u32" },
            Grid {
                name: "lrvtest.heights",
                source: "roms/lrvtest/maps/heights.json",
                element: "f32",
            },
            Grid { name: "lrvtest.nav", source: "roms/lrvtest/maps/nav.json", element: "u32" },
        ],
    )
}

fn pack_scene(
    root: &Path,
    name: &str,
    manifest_rel: &str,
    state_rel: &str,
    guest_wasm: &str,
    grids: &[Grid],
) -> anyhow::Result<()> {
    let out = root.join("roms/out");
    fs::create_dir_all(&out)?;

    // Read the per-scene manifest and inject the ROM metadata fields.
    let mut value: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(root.join(manifest_rel))?)?;
    let obj = value.as_object_mut().context("manifest must be a JSON object")?;
    obj.insert("format_version".into(), serde_json::json!(1));
    obj.insert("entrypoint".into(), serde_json::json!(name));
    obj.insert("state".into(), serde_json::json!("state.json"));
    obj.insert("host_features".into(), serde_json::json!(true));
    obj.insert("trusted".into(), serde_json::json!(true));
    obj.insert(
        "code".into(),
        serde_json::json!([{ "name": "main", "src": format!("/code/{guest_wasm}") }]),
    );
    obj.insert(
        "grids".into(),
        serde_json::json!(grids
            .iter()
            .map(|g| serde_json::json!({ "name": g.name, "src": format!("/data/{}.bin", g.name) }))
            .collect::<Vec<_>>()),
    );

    let manifest_json = serde_json::to_string_pretty(&value)?;
    let manifest: RomManifest = serde_json::from_str(&manifest_json)?;

    let mut resources = ResourceSet::default();
    let res = root.join("roms/out/res");
    let code = root.join("roms/out/code");
    let anims = root.join("roms/out/animations");

    for t in &manifest.manifest.textures {
        let bytes = fs::read(res.join(file_name(&t.src)))?;
        resources.insert(ResourceKind::Texture, t.name.clone(), bytes);
    }
    for f in &manifest.manifest.sdf_fonts {
        let bytes = fs::read(res.join(file_name(&f.metrics)))?;
        resources.insert(ResourceKind::Font, f.name.clone(), bytes);
    }
    for c in &manifest.code {
        let bytes = fs::read(code.join(file_name(&c.src)))?;
        resources.insert(ResourceKind::Code, c.name.clone(), bytes);
    }
    for a in &manifest.manifest.animations {
        if let Some(meta) = &a.metadata {
            let bytes = fs::read(anims.join(file_name(meta)))?;
            resources.insert(ResourceKind::Animation, a.name.clone(), bytes);
        }
    }
    for g in grids {
        let raw: serde_json::Value =
            serde_json::from_str(&fs::read_to_string(root.join(g.source))?)?;
        let arr = raw.as_array().context("grid source must be a JSON array")?;
        let bytes = match g.element {
            "u32" => {
                encode_u32(&arr.iter().map(|v| v.as_u64().unwrap_or(0) as u32).collect::<Vec<_>>())
            }
            "f32" => encode_f32(
                &arr.iter().map(|v| v.as_f64().unwrap_or(0.0) as f32).collect::<Vec<_>>(),
            ),
            other => anyhow::bail!("unknown grid element type `{other}`"),
        };
        resources.insert(ResourceKind::Grid, g.name.to_string(), bytes);
    }
    for v in &manifest.manifest.vehicles {
        let bytes = fs::read(res.join(file_name(&v.src)))?;
        resources.insert(ResourceKind::Vehicle, v.name.clone(), bytes);
    }

    let state = fs::read_to_string(root.join(state_rel))?;

    let rom = Rom { manifest, manifest_json, resources, state };
    let bytes = rom.pack()?;
    fs::write(out.join(format!("{name}.rom")), bytes)?;
    println!("wrote roms/out/{name}.rom");
    Ok(())
}

/// Strip the leading `/` and any directory prefix from a manifest path.
fn file_name(path: &str) -> &str {
    path.trim_start_matches('/').rsplit('/').next().unwrap_or(path)
}

fn encode_u32(vals: &[u32]) -> Vec<u8> {
    let mut out = Vec::with_capacity(vals.len() * 4);
    for v in vals {
        out.extend_from_slice(&v.to_le_bytes());
    }
    out
}

fn encode_f32(vals: &[f32]) -> Vec<u8> {
    let mut out = Vec::with_capacity(vals.len() * 4);
    for v in vals {
        out.extend_from_slice(&v.to_le_bytes());
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use classic_rom::RomArchive;

    #[test]
    fn pack_scene_round_trips_grids_and_state() {
        let dir = std::env::temp_dir().join(format!("xtask-test-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(dir.join("scene/maps")).unwrap();
        fs::create_dir_all(dir.join("roms/out/res")).unwrap();
        fs::create_dir_all(dir.join("roms/out/code")).unwrap();
        fs::create_dir_all(dir.join("roms/out/animations")).unwrap();

        fs::write(
            dir.join("scene/manifest.json"),
            r#"{"shaders":[],"textures":[],"sdf_fonts":[],"animations":[]}"#,
        )
        .unwrap();
        fs::write(
            dir.join("scene/state.json"),
            r#"{"entities":{"tilemap":{"components":[{"type":"Tilemap","position":[0,0,0],"scale":[45,45,1],"size_x":2,"size_y":2,"tile_set":"x","tile_pixel_size":[32,32],"max_tile":8,"tiles_grid":"demo.tiles"}]}}}"#,
        )
        .unwrap();
        fs::write(dir.join("scene/maps/tiles.json"), "[1,2,3,4]").unwrap();
        fs::write(dir.join("roms/out/code/demo.wasm"), b"\0asm").unwrap();

        pack_scene(
            &dir,
            "demo",
            "scene/manifest.json",
            "scene/state.json",
            "demo.wasm",
            &[Grid { name: "demo.tiles", source: "scene/maps/tiles.json", element: "u32" }],
        )
        .unwrap();

        let rom_bytes = fs::read(dir.join("roms/out/demo.rom")).unwrap();
        let archive = RomArchive::from_bytes(&rom_bytes).unwrap();
        let rom = Rom::load(&archive).unwrap();

        assert_eq!(rom.manifest.entrypoint, "demo");
        assert_eq!(
            rom.resources.grids().get("demo.tiles").unwrap(),
            &[1u8, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0][..]
        );
        assert!(rom.state.contains("tiles_grid"));

        fs::remove_dir_all(&dir).unwrap();
    }
}
