/// Axis-aligned rectangle. Used by quadtree, colliders, and layout.
///
/// Matches the TS `Rect` interface (`types.ts:118-123`).
#[derive(Clone, Copy, Debug, Default)]
pub struct Rect {
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
}

impl Rect {
    pub fn new(x: f32, y: f32, width: f32, height: f32) -> Self {
        Self { x, y, width, height }
    }

    pub fn intersects(&self, other: &Rect) -> bool {
        self.x <= other.x + other.width
            && self.x + self.width >= other.x
            && self.y <= other.y + other.height
            && self.y + self.height >= other.y
    }

    /// Whether the point `(px, py)` lies inside (or on) this rect.
    pub fn contains(&self, px: f32, py: f32) -> bool {
        px >= self.x && px <= self.x + self.width && py >= self.y && py <= self.y + self.height
    }
}

/// Collider event names from `collision.ts:138`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ColliderEvent {
    Enter,
    Exit,
    Click,
    Selection,
    SelectionTemp,
}

/// A manifest entry for a shader.
#[derive(Clone, Debug, serde::Deserialize)]
pub struct ShaderInfo {
    pub name: String,
    pub vertex: String,
    pub fragment: String,
    pub attr: Vec<String>,
    pub unif: Vec<String>,
}

/// A manifest entry for a texture.
#[derive(Clone, Debug, serde::Deserialize)]
pub struct TextureManifestEntry {
    pub name: String,
    pub src: String,
}

/// A manifest entry for an SDF font.
#[derive(Clone, Debug, serde::Deserialize)]
pub struct SdfFontManifestEntry {
    pub name: String,
    pub metrics: String,
}

/// A manifest entry for an animation.
#[derive(Clone, Debug, serde::Deserialize)]
pub struct AnimationData {
    pub name: String,
    pub src: String,
    pub rate: f32,
    pub sequence: Vec<u32>,
    /// Per-sequence-entry visual offsets in iso units. Missing entries are zero.
    #[serde(default)]
    pub offsets: Vec<[f32; 3]>,
}

/// The resource manifest (matches `public/manifest.json`).
#[derive(Clone, Debug, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Manifest {
    pub shaders: Vec<ShaderInfo>,
    pub textures: Vec<TextureManifestEntry>,
    #[serde(default)]
    pub sdf_fonts: Vec<SdfFontManifestEntry>,
    #[serde(default)]
    pub animations: Vec<AnimationData>,
}

/// One component in a serialized entity from `state.json`.
///
/// The `type` field identifies the component; everything else is
/// deserialized by the component's own serde impl.
#[derive(Clone, Debug, serde::Deserialize)]
pub struct EntityComponentData {
    #[serde(rename = "type")]
    pub comp_type: String,
    #[serde(flatten)]
    pub fields: serde_json::Value,
}

/// A serialized entity from `state.json`.
#[derive(Clone, Debug, serde::Deserialize)]
pub struct EntityData {
    pub components: Vec<EntityComponentData>,
}

/// Top-level `state.json` shape.
#[derive(Clone, Debug, serde::Deserialize)]
pub struct StateData {
    pub entities: std::collections::HashMap<String, EntityData>,
}

/// Glyph metrics for a single character in an SDF atlas.
#[derive(Clone, Copy, Debug, serde::Deserialize)]
pub struct GlyphMetrics {
    pub x: f32,
    pub y: f32,
    pub w: f32,
    pub h: f32,
    #[serde(rename = "xOffset")]
    pub x_offset: f32,
    #[serde(rename = "yOffset")]
    pub y_offset: f32,
    #[serde(rename = "xAdvance")]
    pub x_advance: f32,
}

/// SDF font metrics (from the `.json` generated by `make-font-atlas.mjs`).
#[derive(Clone, Debug, serde::Deserialize)]
pub struct SdfFontMetrics {
    pub name: String,
    pub family: String,
    #[serde(rename = "atlasSize")]
    pub atlas_size: [f32; 2],
    #[serde(rename = "glyphSize")]
    pub glyph_size: f32,
    #[serde(default)]
    pub spread: f32,
    pub baseline: f32,
    #[serde(rename = "lineHeight")]
    pub line_height: f32,
    pub glyphs: std::collections::HashMap<String, GlyphMetrics>,
}

/// Loading-progress weight constants.
/// Port of `utils.ts:171-177`.
pub const MANIFEST_WEIGHT: f32 = 2.0;
pub const SHADER_FETCH_WEIGHT: f32 = 2.0;
pub const SHADER_COMPILE_WEIGHT: f32 = 1.0;
pub const BUFFERS_WEIGHT: f32 = 1.0;
pub const TEXTURE_WEIGHT: f32 = 1.0;
pub const SDF_FONT_WEIGHT: f32 = 1.0;
pub const ANIMATIONS_WEIGHT: f32 = 1.0;

/// Estimate total loading-progress weight for a manifest.
/// Port of `utils.ts:179-187`.
pub fn estimate_manifest_weight(m: &Manifest) -> f32 {
    MANIFEST_WEIGHT
        + m.shaders.len() as f32 * (SHADER_FETCH_WEIGHT + SHADER_COMPILE_WEIGHT)
        + BUFFERS_WEIGHT
        + m.textures.len() as f32 * TEXTURE_WEIGHT
        + m.sdf_fonts.len() as f32 * SDF_FONT_WEIGHT
        + ANIMATIONS_WEIGHT
}

/// The 2D viewport size driven by canvas dimensions.
#[derive(Clone, Copy, Debug)]
pub struct Viewport {
    pub width: f32,
    pub height: f32,
}

impl Viewport {
    pub fn new(width: f32, height: f32) -> Self {
        Self { width, height }
    }

    pub fn aspect(&self) -> f32 {
        self.width / self.height
    }

    /// Build an orthographic projection matching `state.ts:355-363`.
    /// Left=0, right=w, bottom=h, top=0, near=-10000, far=10000.
    pub fn ortho_matrix(&self) -> glam::Mat4 {
        glam::Mat4::orthographic_rh(0.0, self.width, self.height, 0.0, -10000.0, 10000.0)
    }
}
