//! `IsoVehicle` simulation: wheeled vehicles driven as a rigid chassis plane
//! (`altitude` + `pitch` + `roll`) fit to the four wheel contacts, with each
//! wheel on a per-wheel suspension spring clamped to a travel envelope
//! (compression + droop) and point-mass moon-gravity jumps, driving a body + 4
//! wheel `IsoSprite`s.
//!
//! Part ground-origin anchors come from the vehicle definition sidecar
//! (generated by the Blender exporter).  `spawn_vehicle` derives per-direction
//! wheel tile offsets from those anchors via the engine's iso transform, so
//! parts composite exactly with nothing measured by hand.  `update_vehicles`
//! runs each frame (after the guest update closures) and pushes
//! positions/frames/anchors/offsets into the five sprites.

mod control;
mod kinematics;
mod sim;
#[cfg(test)]
mod tests;

use classic_core::tilemap::{sample_height_mesh, PPM_TARGET};

pub use kinematics::dir_index;

/// Vertical acceleration (metres/s²) — the `40 px/s²` hop re-expressed at
/// `PPM_TARGET` px/m, kept equivalent so the moon-gravity feel is unchanged.
const MOON_GRAVITY: f32 = 40.0 / PPM_TARGET;
/// Per-wheel suspension spring stiffness (per-second²; the same in px and m).
const SUSP_STIFFNESS: f32 = 60.0;
/// Per-wheel suspension damping (1/s).
const SUSP_DAMPING: f32 = 15.0;
/// Upward wheel compression as a fraction of the derived downward droop.  The
/// absolute travel limits are derived per-vehicle from the def geometry at
/// spawn (`spawn_vehicle`): the droop is the vertical reach the baked tilt
/// frames provide at a wheel, and the compression is this fraction of it, so a
/// single-wheel bump compresses the wheel more than it lifts the body.
const COMPRESS_RATIO: f32 = 0.5;

/// Wheel entity-name suffixes, in `[fl, fr, rl, rr]` order (matches the
/// vehicle-definition part order emitted by the exporter).
const WHEEL_SUFFIXES: [&str; 4] = ["Fl", "Fr", "Rl", "Rr"];

/// Sprite-sheet direction count (matches the `[[f32; 2]; 8]` anchor arrays and
/// `dir_index`).
const DIRECTIONS: u32 = 8;

/// Body pitch/roll spring stiffness (rad/s² per rad of error).  Kept
/// underdamped (with `SPRING_DAMPING`) so the body bobs with momentum rather
/// than snapping to the terrain.
const SPRING_STIFFNESS: f32 = 40.0;
/// Body pitch/roll spring damping (1/s).
const SPRING_DAMPING: f32 = 8.0;
/// Nose-down pitch target (radians) while the body is airborne (e.g. falling
/// off a cliff).
const AIRBORNE_PITCH: f32 = -0.26;

/// Distance from the final waypoint (in tiles) at which the pure-pursuit
/// follower considers the goal reached and stops.
const GOAL_TOLERANCE: f32 = 0.5;

/// Cost multiplier for a downward "jump" step in A* (`>= 1.0`).  A mild
/// penalty makes the vehicle prefer flat routes but take a jump when it
/// clearly shortens the path.
const JUMP_COST: f32 = 1.3;

/// Heading error (radians) above which the vehicle shifts into reverse to
/// reorient rather than arcing forward off-traversable.
const REVERSE_ENTER: f32 = 100.0f32.to_radians();
/// Heading error (radians) below which the vehicle shifts back to forward
/// (hysteresis around [`REVERSE_ENTER`]).
const REVERSE_EXIT: f32 = 70.0f32.to_radians();

/// The outcome of submitting a vehicle path request via [`Engine::vehicle_goto`].
pub enum VehicleGotoSubmit {
    /// Vehicle is airborne; the guest should re-issue next frame.
    Airborne,
    /// No entity with that name (drop the request).
    NoVehicle,
    /// Request submitted; poll with [`Engine::vehicle_goto_poll`].
    Submitted(u64),
}

/// The outcome of polling a vehicle path request via [`Engine::vehicle_goto_poll`].
pub enum VehicleGotoPoll {
    /// The search is still running.
    Pending,
    /// A route was found; carries the waypoints to install on the vehicle.
    Accepted(Vec<[i32; 2]>),
    /// No route exists (drop the request).
    NoPath,
}

/// The state of the single in-flight (or cached) non-mutating reachability
/// probe tracked by [`Engine::vehicle_probe`].  The result is cached per target
/// so an unchanged probe target doesn't re-run A* every frame.
pub struct PreviewProbe {
    pub name: String,
    pub target: (i32, i32),
    pub state: PreviewProbeState,
}

/// The in-flight/cached phase of a [`PreviewProbe`].
#[derive(Clone, Copy)]
pub enum PreviewProbeState {
    /// Search running on the worker; poll `id` via `poll_vehicle_path`.
    Pending { id: u64 },
    /// Search finished; `reachable` is the cached answer.
    Done { reachable: bool },
}

/// A terrain-height sampler snapshot, cloned once per frame so the mutation
/// pass can sample heights without re-borrowing the world.
struct TerrainSnapshot {
    size_x: i32,
    size_y: i32,
    heights: Vec<f32>,
}

impl TerrainSnapshot {
    /// Terrain height in **world metres** (the unit the vehicle sim now lives in).
    fn height(&self, x: f32, y: f32) -> f32 {
        sample_height_mesh(&self.heights, self.size_x, self.size_y, x, y)
    }
}

/// The values pushed into the body + wheel sprites each frame.
struct VehicleWrite {
    body: [f32; 3],
    /// Body lift above its own terrain in **world metres** (`frame_offset.z`).
    body_altitude: f32,
    body_anchor: [f32; 2],
    direction: u32,
    body_frame: f32,
    wheel_xy: [[f32; 2]; 4],
    /// Per-wheel lift above its terrain in **world metres** (`frame_offset.z`).
    wheel_altitude: [f32; 4],
    wheel_z: [f32; 4],
    wheel_anchors: [[f32; 2]; 4],
    steer_index: u32,
}
