name: Deploy to GitHub Pages

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
                  token: ${{ secrets.GH_PAT }}

            - uses: dtolnay/rust-toolchain@stable

            - uses: Swatinem/rust-cache@v2
              with:
                  workspaces: apps/web -> target

            - name: Generate assets + ROMs
              run: cargo xtask all

            - name: Install trunk
              run: cargo install trunk --locked

            - name: Build web app
              run: |
                cd apps/web
                trunk build index.html --release

            - uses: peaceiris/actions-gh-pages@v4
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  external_repository: guilledk/guilledk.github.io
                  publish_dir: apps/web/dist
                  publish_branch: master
                  force_orphan: true
