name: Deploy to GitHub Pages

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
                  token: ${{ secrets.GH_PAT }}
            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm
            - run: npm ci
            - run: npm run assets
            - run: npm run build
            - uses: peaceiris/actions-gh-pages@v4
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  external_repository: guilledk/guilledk.github.io
                  publish_dir: dist
                  publish_branch: master
                  force_orphan: true
