//! `IsoVehicle` simulation: wheeled vehicles with per-wheel suspension and
//! point-mass moon-gravity jumps, driving a body + 4 wheel `IsoSprite`s.
//!
//! Part ground-origin anchors come from the vehicle definition sidecar
//! (generated by the Blender exporter).  `spawn_vehicle` derives per-direction
//! wheel tile offsets from those anchors via the engine's iso transform, so
//! parts composite exactly with nothing measured by hand.  `update_vehicles`
//! runs each frame (after the guest update closures) and pushes
//! positions/frames/anchors/offsets into the five sprites.

use classic_core::components::{DebugName, IsoSprite, IsoVehicle, RoleKind, Tilemap, Transform};
use classic_core::math::cartesian_to_iso_4;
use classic_core::tilemap::bilinear_height;
use glam::{Vec2, Vec3};

use crate::Engine;

/// Vertical acceleration (pixels/s²) — tuned for a floaty-but-bounded hop.
const MOON_GRAVITY: f32 = 40.0;
/// Per-wheel suspension spring stiffness (pixels per pixel of deflection / s²).
const SUSP_STIFFNESS: f32 = 60.0;
/// Per-wheel suspension damping.
const SUSP_DAMPING: f32 = 15.0;
/// How far wheels can extend below the body before hanging, in pixels.  This
/// is the suspension travel limit: a wheel whose terrain drops below
/// `body - WHEEL_DROOP` hangs rather than extending to the terrain.  Must stay
/// above the steepest slope drop between the body center and a wheel (~14 px on
/// the ramp course), or wheels float off gentle slopes.
const WHEEL_DROOP: f32 = 20.0;

/// Wheel entity-name suffixes, in `[fl, fr, rl, rr]` order (matches the
/// vehicle-definition part order emitted by the exporter).
const WHEEL_SUFFIXES: [&str; 4] = ["Fl", "Fr", "Rl", "Rr"];

/// Sprite-sheet direction count (matches the `[[f32; 2]; 8]` anchor arrays and
/// `dir_index`).
const DIRECTIONS: u32 = 8;

/// Body pitch/roll spring stiffness (rad/s² per rad of error).  Kept
/// underdamped (with `SPRING_DAMPING`) so the body bobs with momentum rather
/// than snapping to the terrain.
const SPRING_STIFFNESS: f32 = 40.0;
/// Body pitch/roll spring damping (1/s).
const SPRING_DAMPING: f32 = 8.0;
/// Nose-down pitch target (radians) while the body is airborne (e.g. falling
/// off a cliff).
const AIRBORNE_PITCH: f32 = -0.26;

/// A terrain-height sampler snapshot, cloned once per frame so the mutation
/// pass can sample heights without re-borrowing the world.
struct TerrainSnapshot {
    size_x: i32,
    size_y: i32,
    height_scale: f32,
    heights: Vec<f32>,
}

impl TerrainSnapshot {
    fn height(&self, x: f32, y: f32) -> f32 {
        bilinear_height(&self.heights, self.size_x, self.size_y, x, y) * self.height_scale
    }
}

/// Map a tile-step delta to a sprite-sheet direction frame (0..7), matching the
/// 8-direction layout used by the assets pipeline (`0=East, 1=SouthEast, …`).
pub fn dir_index(dx: i32, dy: i32) -> usize {
    match (dx.signum(), dy.signum()) {
        (1, 0) => 0,
        (1, 1) => 1,
        (0, 1) => 2,
        (-1, 1) => 3,
        (-1, 0) => 4,
        (-1, -1) => 5,
        (0, -1) => 6,
        (1, -1) => 7,
        _ => 0,
    }
}

/// Quantize a signed pitch angle (radians) to a pitch frame index in
/// `0..pitch_levels`, mapping `[-pitch_max, +pitch_max]` onto the frame range:
/// `0` = nose-down, `(pitch_levels - 1) / 2` = level (odd counts),
/// `pitch_levels - 1` = nose-up.
fn pitch_index(angle: f32, pitch_max: f32, pitch_levels: u32) -> u32 {
    let levels = pitch_levels.max(1);
    if levels <= 1 {
        return 0;
    }
    let max = pitch_max.abs().max(1e-4);
    let t = (angle / max).clamp(-1.0, 1.0);
    let idx = ((t + 1.0) * 0.5 * (levels - 1) as f32).round() as u32;
    idx.min(levels - 1)
}

/// Advance a body pitch/roll spring one step (semi-implicit Euler), returning
/// the new `(angle, vel)`.  Underdamped, so the body bobs with momentum.
fn step_spring(angle: f32, vel: f32, target: f32, dt: f32) -> (f32, f32) {
    let accel = SPRING_STIFFNESS * (target - angle) - SPRING_DAMPING * vel;
    let new_vel = vel + accel * dt;
    (angle + new_vel * dt, new_vel)
}

/// A part's anchors as a fixed 8-slot array (padded/truncated to 8 directions).
fn anchors8(anchors: &[[f32; 2]]) -> [[f32; 2]; 8] {
    let mut out = [[0.5f32, 0.5f32]; 8];
    for (i, a) in anchors.iter().take(8).enumerate() {
        out[i] = *a;
    }
    out
}

/// Derive per-wheel, per-direction tile-space offsets from the part anchors.
///
/// `delta_px = (wheel_anchor - body_anchor) * cell` is the wheel's screen
/// displacement from the body origin in the sprite's own frame; converting it
/// through the engine's iso transform yields the tile offset that reproduces
/// that displacement exactly.
fn derive_wheel_offsets(
    body_anchors: &[[f32; 2]; 8],
    wheel_anchors: &[[[f32; 2]; 8]; 4],
    cell: [f32; 2],
    tile_scale: f32,
) -> [[[f32; 2]; 8]; 4] {
    let mut offsets = [[[0.0f32; 2]; 8]; 4];
    let inv_scale = 1.0 / tile_scale.max(0.001);
    for (i, anchors) in wheel_anchors.iter().enumerate() {
        for d in 0..8 {
            let dx = (anchors[d][0] - body_anchors[d][0]) * cell[0];
            let dy = (anchors[d][1] - body_anchors[d][1]) * cell[1];
            let iso = cartesian_to_iso_4().transform_point3(Vec3::new(dx, dy, 0.0));
            offsets[i][d] = [iso.x * inv_scale, iso.y * inv_scale];
        }
    }
    offsets
}

/// The values pushed into the body + wheel sprites each frame.
struct VehicleWrite {
    body: [f32; 3],
    body_offset_y: f32,
    body_anchor: [f32; 2],
    direction: u32,
    body_frame: f32,
    wheel_xy: [[f32; 2]; 4],
    wheel_off_y: [f32; 4],
    wheel_z: [f32; 4],
    wheel_anchors: [[f32; 2]; 4],
}

impl Engine {
    /// Snapshot the tilemap's terrain data (cloned once per frame).
    fn vehicle_terrain(&self) -> Option<TerrainSnapshot> {
        let tm_entity = self.entity_by_role(RoleKind::Tilemap)?;
        let tm = self.world.get::<&Tilemap>(tm_entity).ok()?;
        Some(TerrainSnapshot {
            size_x: tm.size_x,
            size_y: tm.size_y,
            height_scale: tm.height_scale,
            heights: tm.height_data.clone(),
        })
    }

    /// Resolve the four wheel entity handles referenced by a vehicle.
    fn vehicle_wheel_handles(&self, ve: hecs::Entity) -> [Option<hecs::Entity>; 4] {
        let Ok(v) = self.world.get::<&IsoVehicle>(ve) else {
            return [None; 4];
        };
        let mut handles = [None; 4];
        for (i, name) in v.wheel_entities.iter().enumerate() {
            handles[i] = self.names.get(name).copied();
        }
        handles
    }

    /// Spawn a vehicle of a declared type: a body entity (with `IsoVehicle`) plus
    /// four wheel `IsoSprite`s, positioned at `(x, y)` with anchors/offsets taken
    /// from the definition sidecar.
    pub fn spawn_vehicle(&mut self, def_name: &str, entity_name: &str, x: f32, y: f32) -> bool {
        let Some(def) = self.vehicles.get(def_name).cloned() else { return false };
        let Some(tm_entity) = self.entity_by_role(RoleKind::Tilemap) else { return false };
        let tile_scale = self.world.get::<&Transform>(tm_entity).map(|t| t.scale.x).unwrap_or(45.0);
        if self.names.contains_key(entity_name) {
            return false;
        }

        let Some(body_part) = def.parts.first().cloned() else { return false };
        if def.parts.len() != 5 {
            return false;
        }

        let body_anchors = anchors8(&body_part.anchors);
        let mut wheel_anchors = [[[0.5f32, 0.5f32]; 8]; 4];
        for (i, anchors) in wheel_anchors.iter_mut().enumerate() {
            *anchors = anchors8(&def.parts[i + 1].anchors);
        }
        let tile_set_size = Vec2::new(def.columns as f32, def.rows as f32);
        let body_tile_set_size = Vec2::new(
            def.columns as f32,
            def.rows as f32 * def.pitch_levels.max(1) as f32 * def.roll_levels.max(1) as f32,
        );
        let cell = if def.cell[0] > 0.0 && def.cell[1] > 0.0 { def.cell } else { [1.0, 1.0] };
        let wheel_tile_offsets =
            derive_wheel_offsets(&body_anchors, &wheel_anchors, cell, tile_scale);

        // Front-rear axle distance in screen pixels, from the derived wheel
        // offsets (front = fl/fr, rear = rl/rr) scaled by the tile scale.
        let wheelbase_px = {
            let front = Vec2::new(
                (wheel_tile_offsets[0][0][0] + wheel_tile_offsets[1][0][0]) * 0.5,
                (wheel_tile_offsets[0][0][1] + wheel_tile_offsets[1][0][1]) * 0.5,
            );
            let rear = Vec2::new(
                (wheel_tile_offsets[2][0][0] + wheel_tile_offsets[3][0][0]) * 0.5,
                (wheel_tile_offsets[2][0][1] + wheel_tile_offsets[3][0][1]) * 0.5,
            );
            (front - rear).length() * tile_scale
        };
        // Left-right axle distance in screen pixels (left = fl/rl, right = fr/rr).
        let track_px = {
            let left = Vec2::new(
                (wheel_tile_offsets[0][0][0] + wheel_tile_offsets[2][0][0]) * 0.5,
                (wheel_tile_offsets[0][0][1] + wheel_tile_offsets[2][0][1]) * 0.5,
            );
            let right = Vec2::new(
                (wheel_tile_offsets[1][0][0] + wheel_tile_offsets[3][0][0]) * 0.5,
                (wheel_tile_offsets[1][0][1] + wheel_tile_offsets[3][0][1]) * 0.5,
            );
            (left - right).length() * tile_scale
        };

        let wheel_names: [String; 4] = WHEEL_SUFFIXES.map(|s| format!("{entity_name}Wheel{s}"));
        let tilemap_name = "tilemap".to_string();

        // Spawn the four wheel sprites.
        for i in 0..4 {
            let sprite = IsoSprite {
                position: Vec3::new(x, y, 0.0),
                scale: Vec3::ONE,
                texture: def.parts[i + 1].texture.clone(),
                tilemap: tilemap_name.clone(),
                frame: 0.0,
                tile_set_size,
                anchor: Vec2::from(wheel_anchors[i][0]),
                frame_offset: Vec3::ZERO,
                footprint: vec![],
            };
            let we = self.world.spawn((sprite, Transform::new(Vec3::new(x, y, 0.0), Vec3::ONE)));
            let _ = self.world.insert_one(we, DebugName(wheel_names[i].clone()));
            self.names.insert(wheel_names[i].clone(), we);
            self.name_order.push(wheel_names[i].clone());
        }

        // Spawn the body entity with the IsoVehicle component.
        let body_sprite = IsoSprite {
            position: Vec3::new(x, y, 0.0),
            scale: Vec3::ONE,
            texture: body_part.texture.clone(),
            tilemap: tilemap_name.clone(),
            frame: 0.0,
            tile_set_size: body_tile_set_size,
            anchor: Vec2::from(body_anchors[0]),
            frame_offset: Vec3::ZERO,
            footprint: vec![],
        };
        let vehicle = IsoVehicle {
            tilemap: tilemap_name,
            wheel_entities: [
                wheel_names[0].clone(),
                wheel_names[1].clone(),
                wheel_names[2].clone(),
                wheel_names[3].clone(),
            ],
            body_anchors,
            wheel_anchors,
            speed: 2.6,
            direction: 0,
            wheel_tile_offsets,
            pitch_levels: def.pitch_levels,
            pitch_max: def.pitch_max_deg.to_radians(),
            wheelbase_px,
            roll_levels: def.roll_levels,
            roll_max: def.roll_max_deg.to_radians(),
            track_px,
            ..Default::default()
        };
        let be = self.world.spawn((
            body_sprite,
            vehicle,
            Transform::new(Vec3::new(x, y, 0.0), Vec3::ONE),
        ));
        let _ = self.world.insert_one(be, DebugName(entity_name.to_string()));
        self.names.insert(entity_name.to_string(), be);
        self.name_order.push(entity_name.to_string());

        self.vehicle_teleport(entity_name, x, y)
    }

    /// Advance every `IsoVehicle` one step: follow the movement path, sample
    /// terrain under each wheel, integrate the point-mass jump + suspension,
    /// and write the five sprites.
    pub fn update_vehicles(&mut self) {
        let delta = self.time.delta;
        let vehicles: Vec<hecs::Entity> =
            self.world.query::<&IsoVehicle>().iter().map(|(e, _)| e).collect();
        if vehicles.is_empty() {
            return;
        }
        let Some(terrain) = self.vehicle_terrain() else {
            return;
        };
        for ve in vehicles {
            self.update_one_vehicle(ve, delta, &terrain);
        }
    }

    fn update_one_vehicle(&mut self, ve: hecs::Entity, delta: f32, terrain: &TerrainSnapshot) {
        let (body_x, body_y) = match self.world.get::<&Transform>(ve) {
            Ok(t) => (t.position.x, t.position.y),
            Err(_) => return,
        };
        let wheel_handles = self.vehicle_wheel_handles(ve);

        let write = {
            let Some(mut v) = self.world.get::<&mut IsoVehicle>(ve).ok() else { return };

            // -- movement along the A* path ---------------------------------
            let mut x = body_x;
            let mut y = body_y;
            if !v.path.is_empty() && v.path_idx < v.path.len() {
                let tx = v.path[v.path_idx][0] as f32 + 0.5;
                let ty = v.path[v.path_idx][1] as f32 + 0.5;
                let dx = tx - x;
                let dy = ty - y;
                let mag = dx.abs() + dy.abs();
                let step = v.speed * delta;
                if mag <= step || mag <= 1e-4 {
                    x = tx;
                    y = ty;
                    v.path_idx += 1;
                } else {
                    let f = step / mag;
                    x += dx * f;
                    y += dy * f;
                }
                let (ddx, ddy) = (dx.round() as i32, dy.round() as i32);
                if ddx != 0 || ddy != 0 {
                    v.direction = dir_index(ddx, ddy) as u32;
                }
            }

            let direction = v.direction as usize;

            // -- wheel ground contacts --------------------------------------
            let mut wheel_xy = [[0.0f32; 2]; 4];
            let mut wheel_ground = [0.0f32; 4];
            for i in 0..4 {
                let (ox, oy) =
                    (v.wheel_tile_offsets[i][direction][0], v.wheel_tile_offsets[i][direction][1]);
                let wx = x + ox;
                let wy = y + oy;
                wheel_xy[i] = [wx, wy];
                wheel_ground[i] = terrain.height(wx, wy);
            }

            // -- body point-mass vertical physics (moon gravity) ------------
            // The body rests on the terrain under its own center (not the
            // highest wheel), so it follows slopes smoothly and only goes
            // airborne when the ground beneath it drops away.
            let body_terrain = terrain.height(x, y);
            v.vel_z -= MOON_GRAVITY * delta;
            v.altitude += v.vel_z * delta;
            let airborne = v.altitude > body_terrain + 0.5;
            if !airborne {
                v.altitude = body_terrain;
                if v.vel_z < 0.0 {
                    v.vel_z = 0.0;
                }
            }
            let body_offset_y = -(v.altitude - body_terrain);

            // -- per-wheel suspension ---------------------------------------
            let mut wheel_off_y = [0.0f32; 4];
            let mut wheel_z = [0.0f32; 4];
            for i in 0..4 {
                // A wheel follows its terrain, but hangs at `WHEEL_DROOP` below
                // the body instead of extending into a gap/depression.
                let target = (v.altitude - WHEEL_DROOP).max(wheel_ground[i]);
                let accel = SUSP_STIFFNESS * (target - v.wheel_h[i]) - SUSP_DAMPING * v.wheel_v[i];
                v.wheel_v[i] += accel * delta;
                v.wheel_h[i] += v.wheel_v[i] * delta;
                // Wheels never sink below the terrain.
                v.wheel_h[i] = v.wheel_h[i].max(wheel_ground[i]);
                wheel_off_y[i] = -(v.wheel_h[i] - wheel_ground[i]);
                wheel_z[i] = v.wheel_h[i];
            }

            let mut wheel_anchors = [[0.0f32; 2]; 4];
            for (i, a) in wheel_anchors.iter_mut().enumerate() {
                *a = v.wheel_anchors[i][direction];
            }

            // -- body pitch (angular spring-damper) --------------------------
            // Target = the terrain surface slope along the heading, from the
            // *instantaneous* wheel ground heights (the spring owns smoothing
            // and bob).  Airborne, the body noses down instead of tracking.
            let pitch_target = if airborne {
                AIRBORNE_PITCH
            } else {
                let front = (wheel_ground[0] + wheel_ground[1]) * 0.5;
                let rear = (wheel_ground[2] + wheel_ground[3]) * 0.5;
                ((front - rear) / v.wheelbase_px.max(1e-4)).atan()
            };
            let (pitch, pitch_vel) = step_spring(v.pitch, v.pitch_vel, pitch_target, delta);
            v.pitch = pitch;
            v.pitch_vel = pitch_vel;
            v.pitch_index = pitch_index(v.pitch, v.pitch_max, v.pitch_levels);

            // -- body roll (side slope, left-up positive) --------------------
            // Target = terrain slope across the vehicle; level when airborne.
            let roll_target = if airborne {
                0.0
            } else {
                let left = (wheel_ground[0] + wheel_ground[2]) * 0.5;
                let right = (wheel_ground[1] + wheel_ground[3]) * 0.5;
                ((left - right) / v.track_px.max(1e-4)).atan()
            };
            let (roll, roll_vel) = step_spring(v.roll, v.roll_vel, roll_target, delta);
            v.roll = roll;
            v.roll_vel = roll_vel;
            v.roll_index = pitch_index(v.roll, v.roll_max, v.roll_levels);

            let body_frame =
                ((v.pitch_index * v.roll_levels + v.roll_index) * DIRECTIONS + v.direction) as f32;

            VehicleWrite {
                body: [x, y, v.altitude],
                body_offset_y,
                body_anchor: v.body_anchors[direction],
                direction: v.direction,
                body_frame,
                wheel_xy,
                wheel_off_y,
                wheel_z,
                wheel_anchors,
            }
        };

        self.apply_pose(ve, &wheel_handles, &write);
    }

    /// Write a computed pose into the body + wheel `Transform`/`IsoSprite`s.
    fn apply_pose(
        &mut self,
        ve: hecs::Entity,
        wheel_handles: &[Option<hecs::Entity>; 4],
        write: &VehicleWrite,
    ) {
        if let Ok(mut tf) = self.world.get::<&mut Transform>(ve) {
            tf.position.x = write.body[0];
            tf.position.y = write.body[1];
            tf.position.z = write.body[2];
        }
        if let Ok(mut s) = self.world.get::<&mut IsoSprite>(ve) {
            s.frame = write.body_frame;
            s.frame_offset.y = write.body_offset_y;
            s.anchor = Vec2::from(write.body_anchor);
        }

        for (i, handle) in wheel_handles.iter().enumerate() {
            let Some(we) = handle else { continue };
            if let Ok(mut tf) = self.world.get::<&mut Transform>(*we) {
                tf.position.x = write.wheel_xy[i][0];
                tf.position.y = write.wheel_xy[i][1];
                tf.position.z = write.wheel_z[i];
            }
            if let Ok(mut s) = self.world.get::<&mut IsoSprite>(*we) {
                s.frame = write.direction as f32;
                s.frame_offset.y = write.wheel_off_y[i];
                s.anchor = Vec2::from(write.wheel_anchors[i]);
            }
        }
    }

    /// Reposition a vehicle (body + 4 wheels) and zero its transient physics.
    /// Used on spawn and whenever the map re-rolls.
    pub fn vehicle_teleport(&mut self, name: &str, x: f32, y: f32) -> bool {
        let Some(&ve) = self.names.get(name) else { return false };
        let Some(terrain) = self.vehicle_terrain() else { return false };
        let wheel_handles = self.vehicle_wheel_handles(ve);

        let write = {
            let Some(mut v) = self.world.get::<&mut IsoVehicle>(ve).ok() else { return false };
            let direction = v.direction as usize;
            v.altitude = terrain.height(x, y);
            v.vel_z = 0.0;
            v.path.clear();
            v.path_idx = 0;

            let mut wheel_xy = [[0.0f32; 2]; 4];
            let mut wheel_z = [0.0f32; 4];
            for i in 0..4 {
                let (ox, oy) =
                    (v.wheel_tile_offsets[i][direction][0], v.wheel_tile_offsets[i][direction][1]);
                let wx = x + ox;
                let wy = y + oy;
                wheel_xy[i] = [wx, wy];
                let gh = terrain.height(wx, wy);
                v.wheel_h[i] = gh;
                v.wheel_v[i] = 0.0;
                wheel_z[i] = gh;
            }
            // Settle the body pitch/roll from the freshly-sampled wheel heights
            // so a teleport onto a slope doesn't flicker through the level frame.
            let front = (v.wheel_h[0] + v.wheel_h[1]) * 0.5;
            let rear = (v.wheel_h[2] + v.wheel_h[3]) * 0.5;
            v.pitch = ((front - rear) / v.wheelbase_px.max(1e-4)).atan();
            v.pitch_vel = 0.0;
            v.pitch_index = pitch_index(v.pitch, v.pitch_max, v.pitch_levels);
            let left = (v.wheel_h[0] + v.wheel_h[2]) * 0.5;
            let right = (v.wheel_h[1] + v.wheel_h[3]) * 0.5;
            v.roll = ((left - right) / v.track_px.max(1e-4)).atan();
            v.roll_vel = 0.0;
            v.roll_index = pitch_index(v.roll, v.roll_max, v.roll_levels);
            let mut wheel_anchors = [[0.0f32; 2]; 4];
            for (i, a) in wheel_anchors.iter_mut().enumerate() {
                *a = v.wheel_anchors[i][direction];
            }
            let body_frame =
                ((v.pitch_index * v.roll_levels + v.roll_index) * DIRECTIONS + v.direction) as f32;

            VehicleWrite {
                body: [x, y, v.altitude],
                body_offset_y: 0.0,
                body_anchor: v.body_anchors[direction],
                direction: v.direction,
                body_frame,
                wheel_xy,
                wheel_off_y: [0.0; 4],
                wheel_z,
                wheel_anchors,
            }
        };

        self.apply_pose(ve, &wheel_handles, &write);
        true
    }

    /// Set a vehicle's destination (integer tile coordinates).  The host runs
    /// its own A* and stores the waypoints on the vehicle.
    pub fn vehicle_goto(&mut self, name: &str, tx: i32, ty: i32) -> bool {
        let Some(&ve) = self.names.get(name) else { return false };
        let Some(tf) = self.world.get::<&Transform>(ve).ok() else { return false };
        let from = (tf.position.x.floor() as i32, tf.position.y.floor() as i32);
        let Some(path) = self.find_path(from, (tx, ty)) else { return false };
        let path: Vec<[i32; 2]> = path.into_iter().map(|(x, y)| [x, y]).collect();
        if let Ok(mut v) = self.world.get::<&mut IsoVehicle>(ve) {
            v.path = path;
            v.path_idx = if v.path.len() > 1 { 1 } else { 0 };
        }
        true
    }

    /// Stop a vehicle, clearing its movement path.
    pub fn vehicle_stop(&mut self, name: &str) -> bool {
        let Some(&ve) = self.names.get(name) else { return false };
        if let Ok(mut v) = self.world.get::<&mut IsoVehicle>(ve) {
            v.path.clear();
            v.path_idx = 0;
            return true;
        }
        false
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use classic_core::components::{NavMesh, Role};
    use classic_core::math::iso_to_cartesian_4;
    use classic_core::types::VehicleDef;

    fn test_tilemap() -> Tilemap {
        Tilemap {
            position: Vec3::ZERO,
            scale: Vec3::new(45.0, 45.0, 1.0),
            size_x: 3,
            size_y: 3,
            tile_set: "tileset".into(),
            tile_pixel_size: [32, 32],
            max_tile: 16,
            tiles_grid: None,
            heights_grid: None,
            data: vec![0; 9],
            height_data: vec![1.0; 16],
            height_scale: 14.0,
            tile_set_pixel_size: [0, 0],
            tiles_per_row: 0,
            mouse_iso_pos: Vec3::ZERO,
            selection_iso_begin: Vec3::new(-1.0, -1.0, -1.0),
            selection_iso_end: Vec3::new(-1.0, -1.0, -1.0),
        }
    }

    #[test]
    fn dir_index_maps_all_eight_directions() {
        assert_eq!(dir_index(1, 0), 0);
        assert_eq!(dir_index(1, 1), 1);
        assert_eq!(dir_index(0, 1), 2);
        assert_eq!(dir_index(-1, 1), 3);
        assert_eq!(dir_index(-1, 0), 4);
        assert_eq!(dir_index(-1, -1), 5);
        assert_eq!(dir_index(0, -1), 6);
        assert_eq!(dir_index(1, -1), 7);
        assert_eq!(dir_index(0, 0), 0);
    }

    #[test]
    fn pitch_index_quantizes_five_levels() {
        let max = 20.0f32.to_radians();

        // Single level (flat) always maps to 0.
        assert_eq!(pitch_index(0.0, max, 1), 0);
        assert_eq!(pitch_index(max, max, 1), 0);

        // Five levels: 0 = nose-down, 2 = level, 4 = nose-up.
        assert_eq!(pitch_index(-max, max, 5), 0);
        assert_eq!(pitch_index(-10.0f32.to_radians(), max, 5), 1);
        assert_eq!(pitch_index(0.0, max, 5), 2);
        assert_eq!(pitch_index(10.0f32.to_radians(), max, 5), 3);
        assert_eq!(pitch_index(max, max, 5), 4);
        // Clamps outside the range.
        assert_eq!(pitch_index(-1.5, max, 5), 0);
        assert_eq!(pitch_index(1.5, max, 5), 4);
    }

    #[test]
    fn pitch_spring_overshoots_and_bobs() {
        let dt = 1.0 / 60.0;
        let target = 0.1;
        let (mut pitch, mut vel) = (0.0f32, 0.0f32);
        let mut max_pitch = 0.0f32;
        for _ in 0..600 {
            let (p, v) = step_spring(pitch, vel, target, dt);
            pitch = p;
            vel = v;
            max_pitch = max_pitch.max(pitch);
        }
        // Underdamped: the body overshoots the target before settling near it.
        assert!(max_pitch > target, "expected overshoot, max {max_pitch} vs target {target}");
        assert!((pitch - target).abs() < 0.01, "did not settle: {pitch}");

        // An airborne target (nose-down) drives the angle negative.
        let (mut pitch, mut vel) = (0.0f32, 0.0f32);
        for _ in 0..600 {
            let (p, v) = step_spring(pitch, vel, AIRBORNE_PITCH, dt);
            pitch = p;
            vel = v;
        }
        assert!(pitch < 0.0, "airborne should pitch nose-down, got {pitch}");

        // A zero (level) roll target settles to ~0.
        let (mut roll, mut vel) = (0.5f32, 0.0f32);
        for _ in 0..600 {
            let (r, v) = step_spring(roll, vel, 0.0, dt);
            roll = r;
            vel = v;
        }
        assert!(roll.abs() < 0.01, "roll should settle to level, got {roll}");
    }

    #[test]
    fn pitch_index_quantizes_three_roll_levels() {
        let max = 20.0f32.to_radians();
        // Three roll levels: 0 = right-up (left-down), 1 = level, 2 = left-up.
        assert_eq!(pitch_index(-max, max, 3), 0);
        assert_eq!(pitch_index(0.0, max, 3), 1);
        assert_eq!(pitch_index(max, max, 3), 2);
    }

    #[test]
    fn derived_offsets_round_trip_through_iso() {
        let cell = [247.0, 247.0];
        let tile_scale = 45.0;
        let body = [[0.5f32, 0.7352f32]; 8];
        // A synthetic front-left wheel anchor per direction; exact values don't
        // matter, only that the round-trip reproduces the anchor delta.
        let mut wheels = [[[0.5f32, 0.5f32]; 8]; 4];
        wheels[0][0] = [0.566155, 0.618458];
        wheels[1][0] = [0.73363, 0.702169];
        wheels[2][0] = [0.211113, 0.795979];
        wheels[3][0] = [0.378535, 0.879716];

        let offsets = derive_wheel_offsets(&body, &wheels, cell, tile_scale);

        for i in 0..4 {
            let delta = Vec3::new(
                (wheels[i][0][0] - body[0][0]) * cell[0],
                (wheels[i][0][1] - body[0][1]) * cell[1],
                0.0,
            );
            let iso = iso_to_cartesian_4().transform_point3(Vec3::new(
                tile_scale * offsets[i][0][0],
                tile_scale * offsets[i][0][1],
                0.0,
            ));
            assert!((iso.x - delta.x).abs() < 1e-3, "wheel {i} x {iso} vs {delta}");
            assert!((iso.y - delta.y).abs() < 1e-3, "wheel {i} y {iso} vs {delta}");
        }
    }

    #[test]
    fn spawn_vehicle_creates_body_and_wheels() {
        let mut engine = Engine::new_for_test();
        let tm = engine.world.spawn((test_tilemap(), Role::new(RoleKind::Tilemap)));
        engine.names.insert("tilemap".into(), tm);

        let def = VehicleDef {
            name: "lrv".into(),
            directions: 8,
            columns: 4,
            rows: 2,
            cell: [247.0, 247.0],
            pitch_levels: 1,
            pitch_max_deg: 20.0,
            roll_levels: 1,
            roll_max_deg: 20.0,
            parts: vec![
                serde_json::from_value(serde_json::json!({
                    "name": "body", "texture": "lrvBody",
                    "anchors": [[0.5, 0.7352], [0.5, 0.7352], [0.5, 0.7352], [0.5, 0.7352],
                                [0.5, 0.7352], [0.5, 0.7352], [0.5, 0.7352], [0.5, 0.7352]]
                }))
                .unwrap(),
                serde_json::from_value(serde_json::json!({
                    "name": "wheel_fl", "texture": "lrvWheelFl",
                    "anchors": [[0.566, 0.618], [0.712, 0.676], [0.733, 0.768], [0.618, 0.841],
                                [0.434, 0.852], [0.288, 0.794], [0.267, 0.702], [0.382, 0.629]]
                }))
                .unwrap(),
                serde_json::from_value(serde_json::json!({
                    "name": "wheel_fr", "texture": "lrvWheelFr",
                    "anchors": [[0.734, 0.702], [0.712, 0.794], [0.566, 0.852], [0.382, 0.841],
                                [0.266, 0.768], [0.288, 0.676], [0.434, 0.618], [0.618, 0.629]]
                }))
                .unwrap(),
                serde_json::from_value(serde_json::json!({
                    "name": "wheel_rl", "texture": "lrvWheelRl",
                    "anchors": [[0.211, 0.796], [0.210, 0.676], [0.378, 0.591], [0.618, 0.590],
                                [0.789, 0.674], [0.790, 0.794], [0.622, 0.880], [0.382, 0.880]]
                }))
                .unwrap(),
                serde_json::from_value(serde_json::json!({
                    "name": "wheel_rr", "texture": "lrvWheelRr",
                    "anchors": [[0.379, 0.880], [0.210, 0.794], [0.211, 0.674], [0.382, 0.590],
                                [0.621, 0.591], [0.790, 0.676], [0.789, 0.796], [0.618, 0.880]]
                }))
                .unwrap(),
            ],
        };
        engine.vehicles.insert("lrv".into(), def);

        assert!(engine.spawn_vehicle("lrv", "lrv", 1.0, 1.0));
        assert!(engine.has_name("lrv"));
        for s in ["lrvWheelFl", "lrvWheelFr", "lrvWheelRl", "lrvWheelRr"] {
            assert!(engine.has_name(s), "missing {s}");
        }
        assert_eq!(engine.get_pos("lrv").map(|(x, y, _)| (x, y)), Some((1.0, 1.0)));

        let body = *engine.names.get("lrv").unwrap();
        {
            let veh = engine.world.get::<&IsoVehicle>(body).unwrap();
            assert_eq!(veh.wheel_entities[0], "lrvWheelFl");
            // Wheel offsets derived (non-zero for the front-left wheel at dir 0).
            assert!(veh.wheel_tile_offsets[0][0][0].abs() > 0.0);
            assert!(veh.wheel_tile_offsets[2][0][0].abs() > 0.0);
            assert!(veh.wheel_tile_offsets[0][0][0] != veh.wheel_tile_offsets[2][0][0]);
        }

        // goto/stop still work after spawn.
        let nav = NavMesh {
            position: Vec3::ZERO,
            scale: Vec3::ONE,
            map_entity: "tilemap".into(),
            tile_set: "navTileset".into(),
            data_grid: None,
            data: vec![1; 9],
            size_x: 3,
            size_y: 3,
        };
        let nm = engine.world.spawn((nav, Role::new(RoleKind::NavMesh)));
        engine.names.insert("navmesh".into(), nm);

        assert!(engine.vehicle_goto("lrv", 2, 1));
        assert!(!engine.world.get::<&IsoVehicle>(body).unwrap().path.is_empty());
        assert!(engine.vehicle_stop("lrv"));
        assert!(engine.world.get::<&IsoVehicle>(body).unwrap().path.is_empty());
    }

    #[test]
    fn spawn_vehicle_sizes_body_sheet_by_pitch_levels() {
        let mut engine = Engine::new_for_test();
        let tm = engine.world.spawn((test_tilemap(), Role::new(RoleKind::Tilemap)));
        engine.names.insert("tilemap".into(), tm);

        // Front wheels anchor to the +X side of the frame, rear wheels to -X,
        // and left/right wheels to distinct +Y/-Y, so both the front-rear
        // wheelbase and the left-right track are non-zero.
        let body = [[0.5, 0.5]];
        let fl = [[0.7, 0.4]];
        let fr = [[0.7, 0.6]];
        let rl = [[0.3, 0.4]];
        let rr = [[0.3, 0.6]];
        let def = VehicleDef {
            name: "lrv".into(),
            directions: 8,
            columns: 4,
            rows: 2,
            cell: [247.0, 247.0],
            pitch_levels: 3,
            pitch_max_deg: 20.0,
            roll_levels: 3,
            roll_max_deg: 20.0,
            parts: vec![
                serde_json::from_value(serde_json::json!({
                    "name": "body", "texture": "lrvBody", "anchors": body
                }))
                .unwrap(),
                serde_json::from_value(serde_json::json!({
                    "name": "wheel_fl", "texture": "lrvWheelFl", "anchors": fl
                }))
                .unwrap(),
                serde_json::from_value(serde_json::json!({
                    "name": "wheel_fr", "texture": "lrvWheelFr", "anchors": fr
                }))
                .unwrap(),
                serde_json::from_value(serde_json::json!({
                    "name": "wheel_rl", "texture": "lrvWheelRl", "anchors": rl
                }))
                .unwrap(),
                serde_json::from_value(serde_json::json!({
                    "name": "wheel_rr", "texture": "lrvWheelRr", "anchors": rr
                }))
                .unwrap(),
            ],
        };
        engine.vehicles.insert("lrv".into(), def);

        assert!(engine.spawn_vehicle("lrv", "lrv", 1.0, 1.0));
        let body_entity = *engine.names.get("lrv").unwrap();
        let wheel = *engine.names.get("lrvWheelFl").unwrap();

        let body_sprite = engine.world.get::<&IsoSprite>(body_entity).unwrap();
        let wheel_sprite = engine.world.get::<&IsoSprite>(wheel).unwrap();
        assert_eq!(body_sprite.tile_set_size, Vec2::new(4.0, 18.0));
        assert_eq!(wheel_sprite.tile_set_size, Vec2::new(4.0, 2.0));

        let veh = engine.world.get::<&IsoVehicle>(body_entity).unwrap();
        assert_eq!(veh.pitch_levels, 3);
        assert!((veh.pitch_max - 20.0f32.to_radians()).abs() < 1e-6);
        assert!(veh.wheelbase_px > 0.0);
        assert_eq!(veh.roll_levels, 3);
        assert!((veh.roll_max - 20.0f32.to_radians()).abs() < 1e-6);
        assert!(veh.track_px > 0.0);
    }
}
