//! `IsoVehicle` simulation: wheeled vehicles with per-wheel suspension and
//! point-mass moon-gravity jumps, driving a body + 4 wheel `IsoSprite`s.
//!
//! Part ground-origin anchors come from the vehicle definition sidecar
//! (generated by the Blender exporter).  `spawn_vehicle` derives per-direction
//! wheel tile offsets from those anchors via the engine's iso transform, so
//! parts composite exactly with nothing measured by hand.  `update_vehicles`
//! runs each frame (after the guest update closures) and pushes
//! positions/frames/anchors/offsets into the five sprites.

use classic_core::components::{DebugName, IsoSprite, IsoVehicle, RoleKind, Tilemap, Transform};
use classic_core::math::cartesian_to_iso_4;
use classic_core::pathfinder::PathPoll;
use classic_core::tilemap::sample_height_mesh;
use glam::{Vec2, Vec3};

use crate::Engine;

/// Vertical acceleration (pixels/s²) — tuned for a floaty-but-bounded hop.
const MOON_GRAVITY: f32 = 40.0;
/// Per-wheel suspension spring stiffness (pixels per pixel of deflection / s²).
const SUSP_STIFFNESS: f32 = 60.0;
/// Per-wheel suspension damping.
const SUSP_DAMPING: f32 = 15.0;
/// How far wheels can extend below the body before hanging, in pixels.  This
/// is the suspension travel limit: a wheel whose terrain drops below
/// `body - WHEEL_DROOP` hangs rather than extending to the terrain.  Must stay
/// above the steepest slope drop between the body center and a wheel (~14 px on
/// the ramp course), or wheels float off gentle slopes.
const WHEEL_DROOP: f32 = 20.0;

/// Wheel entity-name suffixes, in `[fl, fr, rl, rr]` order (matches the
/// vehicle-definition part order emitted by the exporter).
const WHEEL_SUFFIXES: [&str; 4] = ["Fl", "Fr", "Rl", "Rr"];

/// Sprite-sheet direction count (matches the `[[f32; 2]; 8]` anchor arrays and
/// `dir_index`).
const DIRECTIONS: u32 = 8;

/// Body pitch/roll spring stiffness (rad/s² per rad of error).  Kept
/// underdamped (with `SPRING_DAMPING`) so the body bobs with momentum rather
/// than snapping to the terrain.
const SPRING_STIFFNESS: f32 = 40.0;
/// Body pitch/roll spring damping (1/s).
const SPRING_DAMPING: f32 = 8.0;
/// Nose-down pitch target (radians) while the body is airborne (e.g. falling
/// off a cliff).
const AIRBORNE_PITCH: f32 = -0.26;

/// Distance from the final waypoint (in tiles) at which the pure-pursuit
/// follower considers the goal reached and stops.
const GOAL_TOLERANCE: f32 = 0.5;

/// Cost multiplier for a downward "jump" step in A* (`>= 1.0`).  A mild
/// penalty makes the vehicle prefer flat routes but take a jump when it
/// clearly shortens the path.
const JUMP_COST: f32 = 1.3;

/// The outcome of submitting a vehicle path request via [`Engine::vehicle_goto`].
pub enum VehicleGotoSubmit {
    /// Vehicle is airborne; the guest should re-issue next frame.
    Airborne,
    /// No entity with that name (drop the request).
    NoVehicle,
    /// Request submitted; poll with [`Engine::vehicle_goto_poll`].
    Submitted(u64),
}

/// The outcome of polling a vehicle path request via [`Engine::vehicle_goto_poll`].
pub enum VehicleGotoPoll {
    /// The search is still running.
    Pending,
    /// A route was found; carries the waypoints to install on the vehicle.
    Accepted(Vec<[i32; 2]>),
    /// No route exists (drop the request).
    NoPath,
}

/// A terrain-height sampler snapshot, cloned once per frame so the mutation
/// pass can sample heights without re-borrowing the world.
struct TerrainSnapshot {
    size_x: i32,
    size_y: i32,
    height_scale: f32,
    heights: Vec<f32>,
}

impl TerrainSnapshot {
    fn height(&self, x: f32, y: f32) -> f32 {
        sample_height_mesh(&self.heights, self.size_x, self.size_y, x, y) * self.height_scale
    }
}

/// Map a tile-step delta to a sprite-sheet direction frame (0..7), matching the
/// 8-direction layout used by the assets pipeline (`0=East, 1=SouthEast, …`).
pub fn dir_index(dx: i32, dy: i32) -> usize {
    match (dx.signum(), dy.signum()) {
        (1, 0) => 0,
        (1, 1) => 1,
        (0, 1) => 2,
        (-1, 1) => 3,
        (-1, 0) => 4,
        (-1, -1) => 5,
        (0, -1) => 6,
        (1, -1) => 7,
        _ => 0,
    }
}

/// The heading angle (tile-space radians, `atan2(dy, dx)`) for a direction
/// frame.  `0` = East (frame 0), `FRAC_PI_2` = South (frame 2), etc.
fn dir_to_heading(dir: u32) -> f32 {
    (dir % 8) as f32 * std::f32::consts::FRAC_PI_4
}

/// Quantize a continuous heading angle to the nearest of the 8 direction
/// frames (0..7), wrapping at `2π`.
fn heading_to_dir(heading: f32) -> u32 {
    let theta = heading.rem_euclid(std::f32::consts::TAU);
    (theta / std::f32::consts::FRAC_PI_4).round() as u32 % 8
}

/// Wrap an angle to `[-π, π]`.
fn wrap_pi(a: f32) -> f32 {
    let mut a = a;
    while a > std::f32::consts::PI {
        a -= std::f32::consts::TAU;
    }
    while a < -std::f32::consts::PI {
        a += std::f32::consts::TAU;
    }
    a
}

/// Lerp a per-direction `[f32; 2]` value (wheel offset or anchor) between the
/// two direction frames straddling a continuous heading.
fn lerp_dir2(vals: &[[f32; 2]; 8], heading: f32) -> [f32; 2] {
    let theta = heading.rem_euclid(std::f32::consts::TAU);
    let dir_f = theta / std::f32::consts::FRAC_PI_4;
    let a = dir_f.floor() as usize % 8;
    let b = (a + 1) % 8;
    let t = dir_f - dir_f.floor();
    [vals[a][0] * (1.0 - t) + vals[b][0] * t, vals[a][1] * (1.0 - t) + vals[b][1] * t]
}

/// Pure-pursuit look-ahead over a waypoint path.
///
/// Returns `(target_x, target_y, next_idx)` where the target is the point
/// `lookahead` tiles along the path polyline from `(x, y)` (interpolated
/// between waypoint centers) and `next_idx` is the index of the waypoint whose
/// segment contains the target.  The caller advances `path_idx` to `next_idx`
/// each frame, which is always monotonic — a forward-only vehicle never
/// backtracks to a corner it already rounded.  Waypoints the vehicle has passed
/// are skipped up front, so a target that lies "behind" the vehicle (e.g. after
/// overshooting a corner) can't make it spin back around.  When the path is
/// exhausted before `lookahead`, the target is the final waypoint center and
/// `next_idx == path.len()`.
fn lookahead(
    path: &[[i32; 2]],
    path_idx: usize,
    x: f32,
    y: f32,
    lookahead: f32,
) -> (f32, f32, usize) {
    let mut idx = path_idx;

    // Skip waypoints whose segment the vehicle has already traversed (its
    // perpendicular projection onto `path[idx] -> path[idx+1]` is past the end).
    while idx + 1 < path.len() {
        let (ax, ay) = (path[idx][0] as f32 + 0.5, path[idx][1] as f32 + 0.5);
        let (bx, by) = (path[idx + 1][0] as f32 + 0.5, path[idx + 1][1] as f32 + 0.5);
        let segx = bx - ax;
        let segy = by - ay;
        let seglen2 = segx * segx + segy * segy;
        let proj = ((x - ax) * segx + (y - ay) * segy) / seglen2.max(1e-6);
        if proj >= 1.0 {
            idx += 1;
        } else {
            break;
        }
    }

    // Walk forward from the vehicle accumulating `lookahead` tiles of distance.
    let mut remaining = lookahead;
    let (mut px, mut py) = (x, y);
    while idx < path.len() {
        let (wx, wy) = (path[idx][0] as f32 + 0.5, path[idx][1] as f32 + 0.5);
        let dx = wx - px;
        let dy = wy - py;
        let seg = (dx * dx + dy * dy).sqrt();
        if remaining <= seg {
            let t = if seg > 1e-6 { remaining / seg } else { 0.0 };
            return (px + dx * t, py + dy * t, idx);
        }
        remaining -= seg;
        px = wx;
        py = wy;
        idx += 1;
    }

    // Path exhausted: target the final waypoint center.
    let (lx, ly) = (path[path.len() - 1][0] as f32 + 0.5, path[path.len() - 1][1] as f32 + 0.5);
    (lx, ly, path.len())
}

/// Quantize a signed pitch angle (radians) to a pitch frame index in
/// `0..pitch_levels`, mapping `[-pitch_max, +pitch_max]` onto the frame range:
/// `0` = nose-down, `(pitch_levels - 1) / 2` = level (odd counts),
/// `pitch_levels - 1` = nose-up.
fn pitch_index(angle: f32, pitch_max: f32, pitch_levels: u32) -> u32 {
    let levels = pitch_levels.max(1);
    if levels <= 1 {
        return 0;
    }
    let max = pitch_max.abs().max(1e-4);
    let t = (angle / max).clamp(-1.0, 1.0);
    let idx = ((t + 1.0) * 0.5 * (levels - 1) as f32).round() as u32;
    idx.min(levels - 1)
}

/// Advance a body pitch/roll spring one step (semi-implicit Euler), returning
/// the new `(angle, vel)`.  Underdamped, so the body bobs with momentum.
fn step_spring(angle: f32, vel: f32, target: f32, dt: f32) -> (f32, f32) {
    let accel = SPRING_STIFFNESS * (target - angle) - SPRING_DAMPING * vel;
    let new_vel = vel + accel * dt;
    (angle + new_vel * dt, new_vel)
}

/// A part's anchors as a fixed 8-slot array (padded/truncated to 8 directions).
fn anchors8(anchors: &[[f32; 2]]) -> [[f32; 2]; 8] {
    let mut out = [[0.5f32, 0.5f32]; 8];
    for (i, a) in anchors.iter().take(8).enumerate() {
        out[i] = *a;
    }
    out
}

/// Derive per-wheel, per-direction tile-space offsets from the part anchors.
///
/// `delta_px = (wheel_anchor - body_anchor) * cell` is the wheel's screen
/// displacement from the body origin in the sprite's own frame; converting it
/// through the engine's iso transform yields the tile offset that reproduces
/// that displacement exactly.
fn derive_wheel_offsets(
    body_anchors: &[[f32; 2]; 8],
    wheel_anchors: &[[[f32; 2]; 8]; 4],
    cell: [f32; 2],
    tile_scale: f32,
) -> [[[f32; 2]; 8]; 4] {
    let mut offsets = [[[0.0f32; 2]; 8]; 4];
    let inv_scale = 1.0 / tile_scale.max(0.001);
    for (i, anchors) in wheel_anchors.iter().enumerate() {
        for d in 0..8 {
            let dx = (anchors[d][0] - body_anchors[d][0]) * cell[0];
            let dy = (anchors[d][1] - body_anchors[d][1]) * cell[1];
            let iso = cartesian_to_iso_4().transform_point3(Vec3::new(dx, dy, 0.0));
            offsets[i][d] = [iso.x * inv_scale, iso.y * inv_scale];
        }
    }
    offsets
}

/// The values pushed into the body + wheel sprites each frame.
struct VehicleWrite {
    body: [f32; 3],
    body_offset_y: f32,
    body_anchor: [f32; 2],
    direction: u32,
    body_frame: f32,
    wheel_xy: [[f32; 2]; 4],
    wheel_off_y: [f32; 4],
    wheel_z: [f32; 4],
    wheel_anchors: [[f32; 2]; 4],
}

impl Engine {
    /// Resolve a vehicle sprite's packed-atlas frame name from its texture and
    /// flat frame index, mirroring the animator's `{texture}_{frame}` naming.
    /// Returns `None` when the texture has no frame table, so the uniform-grid
    /// `frame`/`tile_set_size` path takes over.
    fn frame_name(
        tables: &std::collections::HashMap<String, classic_core::types::FrameTable>,
        texture: &str,
        frame: f32,
    ) -> Option<String> {
        tables.contains_key(texture).then(|| format!("{texture}_{}", frame as u32))
    }

    /// Snapshot the tilemap's terrain data (cloned once per frame).
    fn vehicle_terrain(&self) -> Option<TerrainSnapshot> {
        let tm_entity = self.entity_by_role(RoleKind::Tilemap)?;
        let tm = self.world.get::<&Tilemap>(tm_entity).ok()?;
        Some(TerrainSnapshot {
            size_x: tm.size_x,
            size_y: tm.size_y,
            height_scale: tm.height_scale,
            heights: tm.height_data.clone(),
        })
    }

    /// Resolve the four wheel entity handles referenced by a vehicle.
    fn vehicle_wheel_handles(&self, ve: hecs::Entity) -> [Option<hecs::Entity>; 4] {
        let Ok(v) = self.world.get::<&IsoVehicle>(ve) else {
            return [None; 4];
        };
        let mut handles = [None; 4];
        for (i, name) in v.wheel_entities.iter().enumerate() {
            handles[i] = self.names.get(name).copied();
        }
        handles
    }

    /// Spawn a vehicle of a declared type: a body entity (with `IsoVehicle`) plus
    /// four wheel `IsoSprite`s, positioned at `(x, y)` with anchors/offsets taken
    /// from the definition sidecar.
    pub fn spawn_vehicle(&mut self, def_name: &str, entity_name: &str, x: f32, y: f32) -> bool {
        let Some(def) = self.vehicles.get(def_name).cloned() else { return false };
        let Some(tm_entity) = self.entity_by_role(RoleKind::Tilemap) else { return false };
        let tile_scale = self.world.get::<&Transform>(tm_entity).map(|t| t.scale.x).unwrap_or(45.0);
        if self.names.contains_key(entity_name) {
            return false;
        }

        let Some(body_part) = def.parts.first().cloned() else { return false };
        if def.parts.len() != 5 {
            return false;
        }

        let body_anchors = anchors8(&body_part.anchors);
        let mut wheel_anchors = [[[0.5f32, 0.5f32]; 8]; 4];
        for (i, anchors) in wheel_anchors.iter_mut().enumerate() {
            *anchors = anchors8(&def.parts[i + 1].anchors);
        }
        let tile_set_size = Vec2::new(def.columns as f32, def.rows as f32);
        let body_tile_set_size = Vec2::new(
            def.columns as f32,
            def.rows as f32 * def.pitch_levels.max(1) as f32 * def.roll_levels.max(1) as f32,
        );
        let cell = if def.cell[0] > 0.0 && def.cell[1] > 0.0 { def.cell } else { [1.0, 1.0] };
        let wheel_tile_offsets =
            derive_wheel_offsets(&body_anchors, &wheel_anchors, cell, tile_scale);

        // Front-rear axle distance in screen pixels, from the derived wheel
        // offsets (front = fl/fr, rear = rl/rr) scaled by the tile scale.
        let wheelbase_px = {
            let front = Vec2::new(
                (wheel_tile_offsets[0][0][0] + wheel_tile_offsets[1][0][0]) * 0.5,
                (wheel_tile_offsets[0][0][1] + wheel_tile_offsets[1][0][1]) * 0.5,
            );
            let rear = Vec2::new(
                (wheel_tile_offsets[2][0][0] + wheel_tile_offsets[3][0][0]) * 0.5,
                (wheel_tile_offsets[2][0][1] + wheel_tile_offsets[3][0][1]) * 0.5,
            );
            (front - rear).length() * tile_scale
        };
        // Left-right axle distance in screen pixels (left = fl/rl, right = fr/rr).
        let track_px = {
            let left = Vec2::new(
                (wheel_tile_offsets[0][0][0] + wheel_tile_offsets[2][0][0]) * 0.5,
                (wheel_tile_offsets[0][0][1] + wheel_tile_offsets[2][0][1]) * 0.5,
            );
            let right = Vec2::new(
                (wheel_tile_offsets[1][0][0] + wheel_tile_offsets[3][0][0]) * 0.5,
                (wheel_tile_offsets[1][0][1] + wheel_tile_offsets[3][0][1]) * 0.5,
            );
            (left - right).length() * tile_scale
        };

        // Collision footprint for pathfinding: explicit def override, else
        // auto-derived from the wheelbase/track — half the wheelbase
        // (front-rear) along the heading axis and half the track (left-right)
        // across it, rounded out.  This matches the vehicle's actual footprint
        // in a single heading rather than the union of all 8 (which
        // over-estimates on diagonal headings).
        let footprint: Vec<(i32, i32)> = match &def.path_footprint {
            Some(fp) => fp.clone(),
            None => {
                let half_x = ((wheelbase_px / tile_scale) * 0.5).ceil() as i32;
                let half_y = ((track_px / tile_scale) * 0.5).ceil() as i32;
                let mut fp = Vec::with_capacity(((half_x * 2 + 1) * (half_y * 2 + 1)) as usize);
                for dy in -half_y..=half_y {
                    for dx in -half_x..=half_x {
                        fp.push((dx, dy));
                    }
                }
                fp
            }
        };

        let wheel_names: [String; 4] = WHEEL_SUFFIXES.map(|s| format!("{entity_name}Wheel{s}"));
        let tilemap_name = "tilemap".to_string();
        // Assign a unique per-instance stencil ghost-group id to the body + all
        // four wheels, so the parts never ghost through each other (but still
        // ghost through terrain and other entities).  Ids live in 1..=255; 0 is
        // reserved for ungrouped sprites.
        let ghost_group = self.next_ghost_group;
        self.next_ghost_group = (self.next_ghost_group % 255) + 1;

        // Spawn the four wheel sprites.
        for i in 0..4 {
            let sprite = IsoSprite {
                position: Vec3::new(x, y, 0.0),
                scale: Vec3::ONE,
                texture: def.parts[i + 1].texture.clone(),
                tilemap: tilemap_name.clone(),
                frame: 0.0,
                frame_name: None,
                tile_set_size,
                anchor: Vec2::from(wheel_anchors[i][0]),
                frame_offset: Vec3::ZERO,
                footprint: vec![],
                ghost_group,
            };
            let we = self.world.spawn((sprite, Transform::new(Vec3::new(x, y, 0.0), Vec3::ONE)));
            let _ = self.world.insert_one(we, DebugName(wheel_names[i].clone()));
            self.names.insert(wheel_names[i].clone(), we);
            self.name_order.push(wheel_names[i].clone());
        }

        // Spawn the body entity with the IsoVehicle component.
        let body_sprite = IsoSprite {
            position: Vec3::new(x, y, 0.0),
            scale: Vec3::ONE,
            texture: body_part.texture.clone(),
            tilemap: tilemap_name.clone(),
            frame: 0.0,
            frame_name: None,
            tile_set_size: body_tile_set_size,
            anchor: Vec2::from(body_anchors[0]),
            frame_offset: Vec3::ZERO,
            footprint: vec![],
            ghost_group,
        };
        let vehicle = IsoVehicle {
            tilemap: tilemap_name,
            wheel_entities: [
                wheel_names[0].clone(),
                wheel_names[1].clone(),
                wheel_names[2].clone(),
                wheel_names[3].clone(),
            ],
            body_anchors,
            wheel_anchors,
            speed: 2.6,
            direction: 0,
            wheel_tile_offsets,
            pitch_levels: def.pitch_levels,
            pitch_max: def.pitch_max_deg.to_radians(),
            wheelbase_px,
            roll_levels: def.roll_levels,
            roll_max: def.roll_max_deg.to_radians(),
            track_px,
            path_footprint: footprint,
            turn_rate: def.turn_rate_deg_per_sec.to_radians(),
            safe_fall_px: def.safe_fall_px,
            ..Default::default()
        };
        let be = self.world.spawn((
            body_sprite,
            vehicle,
            Transform::new(Vec3::new(x, y, 0.0), Vec3::ONE),
        ));
        let _ = self.world.insert_one(be, DebugName(entity_name.to_string()));
        self.names.insert(entity_name.to_string(), be);
        self.name_order.push(entity_name.to_string());

        self.vehicle_teleport(entity_name, x, y)
    }

    /// Advance every `IsoVehicle` one step: follow the movement path, sample
    /// terrain under each wheel, integrate the point-mass jump + suspension,
    /// and write the five sprites.
    pub fn update_vehicles(&mut self) {
        let delta = self.time.delta;
        let vehicles: Vec<hecs::Entity> =
            self.world.query::<&IsoVehicle>().iter().map(|(e, _)| e).collect();
        if vehicles.is_empty() {
            return;
        }
        let Some(terrain) = self.vehicle_terrain() else {
            return;
        };
        for ve in vehicles {
            self.update_one_vehicle(ve, delta, &terrain);
        }
    }

    fn update_one_vehicle(&mut self, ve: hecs::Entity, delta: f32, terrain: &TerrainSnapshot) {
        let (body_x, body_y) = match self.world.get::<&Transform>(ve) {
            Ok(t) => (t.position.x, t.position.y),
            Err(_) => return,
        };
        let wheel_handles = self.vehicle_wheel_handles(ve);

        let write = {
            let Some(mut v) = self.world.get::<&mut IsoVehicle>(ve).ok() else { return };

            // -- movement along the A* path (bounded-turn, forward-only) ----
            let mut x = body_x;
            let mut y = body_y;
            if !v.path.is_empty() {
                // Arrive once the final waypoint is within tolerance; snap to
                // its center and stop.
                let goal = (
                    v.path[v.path.len() - 1][0] as f32 + 0.5,
                    v.path[v.path.len() - 1][1] as f32 + 0.5,
                );
                let dx = goal.0 - x;
                let dy = goal.1 - y;
                if dx * dx + dy * dy <= GOAL_TOLERANCE * GOAL_TOLERANCE {
                    x = goal.0;
                    y = goal.1;
                    v.path.clear();
                    v.path_idx = 0;
                } else {
                    // Pure-pursuit: lead the target by ~1.5× the minimum
                    // turning radius (speed / turn_rate) so the vehicle arcs
                    // through corners rather than orbiting a waypoint inside
                    // its turning circle.
                    let turn_radius = v.speed / v.turn_rate.max(1e-3);
                    let lookahead_dist = (turn_radius * 1.5).max(1.0);
                    let (gx, gy, next_idx) = lookahead(&v.path, v.path_idx, x, y, lookahead_dist);
                    v.path_idx = next_idx;

                    // Steer the heading toward the look-ahead target, bounded
                    // by the max turn rate.
                    let desired = (gy - y).atan2(gx - x);
                    let err = wrap_pi(desired - v.heading);
                    let max_turn = v.turn_rate * delta;
                    v.heading = wrap_pi(v.heading + err.clamp(-max_turn, max_turn));

                    // Advance forward only (a wheeled vehicle never reverses).
                    let step = v.speed * delta;
                    x += v.heading.cos() * step;
                    y += v.heading.sin() * step;
                }
            }

            // Quantize the continuous heading for the 8-way sprite sheets.
            v.direction = heading_to_dir(v.heading);

            // -- wheel ground contacts --------------------------------------
            let mut wheel_xy = [[0.0f32; 2]; 4];
            let mut wheel_ground = [0.0f32; 4];
            for i in 0..4 {
                let [ox, oy] = lerp_dir2(&v.wheel_tile_offsets[i], v.heading);
                let wx = x + ox;
                let wy = y + oy;
                wheel_xy[i] = [wx, wy];
                wheel_ground[i] = terrain.height(wx, wy);
            }

            // -- body point-mass vertical physics (moon gravity) ------------
            // The body rests on the terrain under its own center (not the
            // highest wheel), so it follows slopes smoothly and only goes
            // airborne when the ground beneath it drops away.
            let body_terrain = terrain.height(x, y);
            v.vel_z -= MOON_GRAVITY * delta;
            v.altitude += v.vel_z * delta;
            let airborne = v.altitude > body_terrain + 0.5;
            if !airborne {
                v.altitude = body_terrain;
                if v.vel_z < 0.0 {
                    v.vel_z = 0.0;
                }
            }
            v.airborne = airborne;
            let body_offset_y = -(v.altitude - body_terrain);

            // -- per-wheel suspension ---------------------------------------
            let mut wheel_off_y = [0.0f32; 4];
            let mut wheel_z = [0.0f32; 4];
            for i in 0..4 {
                // A wheel follows its terrain, but hangs at `WHEEL_DROOP` below
                // the body instead of extending into a gap/depression.
                let target = (v.altitude - WHEEL_DROOP).max(wheel_ground[i]);
                let accel = SUSP_STIFFNESS * (target - v.wheel_h[i]) - SUSP_DAMPING * v.wheel_v[i];
                v.wheel_v[i] += accel * delta;
                v.wheel_h[i] += v.wheel_v[i] * delta;
                // Wheels never sink below the terrain.
                v.wheel_h[i] = v.wheel_h[i].max(wheel_ground[i]);
                wheel_off_y[i] = -(v.wheel_h[i] - wheel_ground[i]);
                wheel_z[i] = v.wheel_h[i];
            }

            let mut wheel_anchors = [[0.0f32; 2]; 4];
            for (i, a) in wheel_anchors.iter_mut().enumerate() {
                *a = lerp_dir2(&v.wheel_anchors[i], v.heading);
            }

            // -- body pitch (angular spring-damper) --------------------------
            // Target = the terrain surface slope along the heading, from the
            // *instantaneous* wheel ground heights (the spring owns smoothing
            // and bob).  Airborne, the body noses down instead of tracking.
            let pitch_target = if airborne {
                AIRBORNE_PITCH
            } else {
                let front = (wheel_ground[0] + wheel_ground[1]) * 0.5;
                let rear = (wheel_ground[2] + wheel_ground[3]) * 0.5;
                ((front - rear) / v.wheelbase_px.max(1e-4)).atan()
            };
            let (pitch, pitch_vel) = step_spring(v.pitch, v.pitch_vel, pitch_target, delta);
            v.pitch = pitch;
            v.pitch_vel = pitch_vel;
            v.pitch_index = pitch_index(v.pitch, v.pitch_max, v.pitch_levels);

            // -- body roll (side slope, left-up positive) --------------------
            // Target = terrain slope across the vehicle; level when airborne.
            let roll_target = if airborne {
                0.0
            } else {
                let left = (wheel_ground[0] + wheel_ground[2]) * 0.5;
                let right = (wheel_ground[1] + wheel_ground[3]) * 0.5;
                ((left - right) / v.track_px.max(1e-4)).atan()
            };
            let (roll, roll_vel) = step_spring(v.roll, v.roll_vel, roll_target, delta);
            v.roll = roll;
            v.roll_vel = roll_vel;
            v.roll_index = pitch_index(v.roll, v.roll_max, v.roll_levels);

            let body_frame =
                ((v.pitch_index * v.roll_levels + v.roll_index) * DIRECTIONS + v.direction) as f32;

            VehicleWrite {
                body: [x, y, v.altitude],
                body_offset_y,
                body_anchor: lerp_dir2(&v.body_anchors, v.heading),
                direction: v.direction,
                body_frame,
                wheel_xy,
                wheel_off_y,
                wheel_z,
                wheel_anchors,
            }
        };

        self.apply_pose(ve, &wheel_handles, &write);
    }

    /// Write a computed pose into the body + wheel `Transform`/`IsoSprite`s.
    fn apply_pose(
        &mut self,
        ve: hecs::Entity,
        wheel_handles: &[Option<hecs::Entity>; 4],
        write: &VehicleWrite,
    ) {
        if let Ok(mut tf) = self.world.get::<&mut Transform>(ve) {
            tf.position.x = write.body[0];
            tf.position.y = write.body[1];
            tf.position.z = write.body[2];
        }
        if let Ok(mut s) = self.world.get::<&mut IsoSprite>(ve) {
            s.frame = write.body_frame;
            s.frame_name = Self::frame_name(&self.frame_tables, &s.texture, write.body_frame);
            s.frame_offset.y = write.body_offset_y;
            s.anchor = Vec2::from(write.body_anchor);
        }

        for (i, handle) in wheel_handles.iter().enumerate() {
            let Some(we) = handle else { continue };
            if let Ok(mut tf) = self.world.get::<&mut Transform>(*we) {
                tf.position.x = write.wheel_xy[i][0];
                tf.position.y = write.wheel_xy[i][1];
                tf.position.z = write.wheel_z[i];
            }
            if let Ok(mut s) = self.world.get::<&mut IsoSprite>(*we) {
                s.frame = write.direction as f32;
                s.frame_name = Self::frame_name(&self.frame_tables, &s.texture, s.frame);
                s.frame_offset.y = write.wheel_off_y[i];
                s.anchor = Vec2::from(write.wheel_anchors[i]);
            }
        }
    }

    /// Reposition a vehicle (body + 4 wheels) and zero its transient physics.
    /// Used on spawn and whenever the map re-rolls.
    pub fn vehicle_teleport(&mut self, name: &str, x: f32, y: f32) -> bool {
        let Some(&ve) = self.names.get(name) else { return false };
        let Some(terrain) = self.vehicle_terrain() else { return false };
        let wheel_handles = self.vehicle_wheel_handles(ve);

        let write = {
            let Some(mut v) = self.world.get::<&mut IsoVehicle>(ve).ok() else { return false };
            let direction = v.direction as usize;
            v.altitude = terrain.height(x, y);
            v.vel_z = 0.0;
            v.airborne = false;
            v.heading = dir_to_heading(v.direction);
            v.path.clear();
            v.path_idx = 0;

            let mut wheel_xy = [[0.0f32; 2]; 4];
            let mut wheel_z = [0.0f32; 4];
            for i in 0..4 {
                let (ox, oy) =
                    (v.wheel_tile_offsets[i][direction][0], v.wheel_tile_offsets[i][direction][1]);
                let wx = x + ox;
                let wy = y + oy;
                wheel_xy[i] = [wx, wy];
                let gh = terrain.height(wx, wy);
                v.wheel_h[i] = gh;
                v.wheel_v[i] = 0.0;
                wheel_z[i] = gh;
            }
            // Settle the body pitch/roll from the freshly-sampled wheel heights
            // so a teleport onto a slope doesn't flicker through the level frame.
            let front = (v.wheel_h[0] + v.wheel_h[1]) * 0.5;
            let rear = (v.wheel_h[2] + v.wheel_h[3]) * 0.5;
            v.pitch = ((front - rear) / v.wheelbase_px.max(1e-4)).atan();
            v.pitch_vel = 0.0;
            v.pitch_index = pitch_index(v.pitch, v.pitch_max, v.pitch_levels);
            let left = (v.wheel_h[0] + v.wheel_h[2]) * 0.5;
            let right = (v.wheel_h[1] + v.wheel_h[3]) * 0.5;
            v.roll = ((left - right) / v.track_px.max(1e-4)).atan();
            v.roll_vel = 0.0;
            v.roll_index = pitch_index(v.roll, v.roll_max, v.roll_levels);
            let mut wheel_anchors = [[0.0f32; 2]; 4];
            for (i, a) in wheel_anchors.iter_mut().enumerate() {
                *a = v.wheel_anchors[i][direction];
            }
            let body_frame =
                ((v.pitch_index * v.roll_levels + v.roll_index) * DIRECTIONS + v.direction) as f32;

            VehicleWrite {
                body: [x, y, v.altitude],
                body_offset_y: 0.0,
                body_anchor: v.body_anchors[direction],
                direction: v.direction,
                body_frame,
                wheel_xy,
                wheel_off_y: [0.0; 4],
                wheel_z,
                wheel_anchors,
            }
        };

        self.apply_pose(ve, &wheel_handles, &write);
        true
    }

    /// Set a vehicle's destination (integer tile coordinates).  Submits a
    /// footprint-, slope- and jump-aware A* request off-thread (or computes it
    /// inline under `synchronous_workers`) and returns a request id to poll
    /// with [`Engine::vehicle_goto_poll`].
    pub fn vehicle_goto(&mut self, name: &str, tx: i32, ty: i32) -> VehicleGotoSubmit {
        let Some(&ve) = self.names.get(name) else {
            classic_core::cl_info!(
                classic_core::instrument::Chan::Path,
                "vehicle_goto: no entity named {name}"
            );
            return VehicleGotoSubmit::NoVehicle;
        };
        let (footprint, pitch_max, roll_max, wheelbase_px, track_px, safe_fall_px) = {
            let Ok(v) = self.world.get::<&IsoVehicle>(ve) else {
                return VehicleGotoSubmit::NoVehicle;
            };
            // Reject new paths while airborne: the vehicle keeps its current
            // trajectory until its wheels touch down again (issue #40).
            if v.airborne {
                classic_core::cl_info!(
                    classic_core::instrument::Chan::Path,
                    "vehicle_goto {name}: airborne, rejecting"
                );
                return VehicleGotoSubmit::Airborne;
            }
            (
                v.path_footprint.clone(),
                v.pitch_max,
                v.roll_max,
                v.wheelbase_px,
                v.track_px,
                v.safe_fall_px,
            )
        };
        let from = {
            let Ok(tf) = self.world.get::<&Transform>(ve) else {
                return VehicleGotoSubmit::NoVehicle;
            };
            (tf.position.x.floor() as i32, tf.position.y.floor() as i32)
        };

        // Allocate a request id.  Shares the `next_path_id` counter with the
        // humanoid `request_path` so ids stay unique in the worker's result map.
        let id = self.next_path_id;
        self.next_path_id = self.next_path_id.wrapping_add(1);

        if !self.synchronous_workers {
            self.ensure_pathfinder();
            if let Some(worker) = self.pathfinder.as_mut() {
                worker.request_vehicle_path(
                    id,
                    from,
                    (tx, ty),
                    footprint,
                    pitch_max,
                    roll_max,
                    wheelbase_px,
                    track_px,
                    safe_fall_px,
                    JUMP_COST,
                );
            }
        } else {
            let poll = match self.find_vehicle_path(
                from,
                (tx, ty),
                &footprint,
                pitch_max,
                roll_max,
                wheelbase_px,
                track_px,
                safe_fall_px,
                JUMP_COST,
            ) {
                Some(path) => {
                    VehicleGotoPoll::Accepted(path.into_iter().map(|(x, y)| [x, y]).collect())
                }
                None => VehicleGotoPoll::NoPath,
            };
            self.sync_vehicle_paths.insert(id, poll);
        }

        self.vehicle_path_entities.insert(id, ve);
        VehicleGotoSubmit::Submitted(id)
    }

    /// Poll a previously submitted vehicle path request (non-blocking).  On
    /// acceptance, the route is installed on the vehicle (`v.path` /
    /// `v.path_idx`) here — the single mutation point shared by the sync and
    /// async paths.
    pub fn vehicle_goto_poll(&mut self, id: u64) -> VehicleGotoPoll {
        let poll = if let Some(poll) = self.sync_vehicle_paths.remove(&id) {
            poll
        } else if let Some(worker) = self.pathfinder.as_mut() {
            match worker.poll_vehicle_path(id) {
                PathPoll::Pending => VehicleGotoPoll::Pending,
                PathPoll::NoPath => VehicleGotoPoll::NoPath,
                PathPoll::Path(cells) => {
                    VehicleGotoPoll::Accepted(cells.into_iter().map(|(x, y)| [x, y]).collect())
                }
            }
        } else {
            VehicleGotoPoll::Pending
        };

        match &poll {
            VehicleGotoPoll::Accepted(path) => {
                if let Some(ve) = self.vehicle_path_entities.remove(&id) {
                    if let Ok(mut v) = self.world.get::<&mut IsoVehicle>(ve) {
                        v.path = path.clone();
                        v.path_idx = if v.path.len() > 1 { 1 } else { 0 };
                    }
                }
            }
            VehicleGotoPoll::NoPath => {
                self.vehicle_path_entities.remove(&id);
            }
            VehicleGotoPoll::Pending => {}
        }

        poll
    }

    /// Stop a vehicle, clearing its movement path.
    pub fn vehicle_stop(&mut self, name: &str) -> bool {
        let Some(&ve) = self.names.get(name) else { return false };
        if let Ok(mut v) = self.world.get::<&mut IsoVehicle>(ve) {
            v.path.clear();
            v.path_idx = 0;
            return true;
        }
        false
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use classic_core::components::{NavMesh, Role};
    use classic_core::math::iso_to_cartesian_4;
    use classic_core::types::{FrameTable, VehicleDef, VehiclePartDef};

    fn test_tilemap() -> Tilemap {
        flat_tilemap(3, 3)
    }

    /// A flat, fully-walkable-looking tilemap of arbitrary size (heights all 1).
    fn flat_tilemap(size_x: i32, size_y: i32) -> Tilemap {
        Tilemap {
            position: Vec3::ZERO,
            scale: Vec3::new(45.0, 45.0, 1.0),
            size_x,
            size_y,
            tile_set: "tileset".into(),
            tile_pixel_size: [32, 32],
            max_tile: 16,
            tiles_grid: None,
            heights_grid: None,
            data: vec![0; (size_x * size_y) as usize],
            height_data: vec![1.0; ((size_x + 1) * (size_y + 1)) as usize],
            height_scale: 14.0,
            tile_set_pixel_size: [0, 0],
            tiles_per_row: 0,
            mouse_iso_pos: Vec3::ZERO,
            selection_iso_begin: Vec3::new(-1.0, -1.0, -1.0),
            selection_iso_end: Vec3::new(-1.0, -1.0, -1.0),
        }
    }

    /// Submit a vehicle goto under `synchronous_workers` (inline search) and
    /// return the poll outcome immediately, mirroring the guest's submit/poll
    /// idiom.  Airborne / unknown-vehicle submissions resolve to `NoPath`.
    fn goto_sync(engine: &mut Engine, name: &str, tx: i32, ty: i32) -> VehicleGotoPoll {
        engine.set_synchronous_workers(true);
        let id = match engine.vehicle_goto(name, tx, ty) {
            VehicleGotoSubmit::Submitted(id) => id,
            VehicleGotoSubmit::Airborne | VehicleGotoSubmit::NoVehicle => {
                return VehicleGotoPoll::NoPath;
            }
        };
        engine.vehicle_goto_poll(id)
    }

    #[test]
    fn dir_index_maps_all_eight_directions() {
        assert_eq!(dir_index(1, 0), 0);
        assert_eq!(dir_index(1, 1), 1);
        assert_eq!(dir_index(0, 1), 2);
        assert_eq!(dir_index(-1, 1), 3);
        assert_eq!(dir_index(-1, 0), 4);
        assert_eq!(dir_index(-1, -1), 5);
        assert_eq!(dir_index(0, -1), 6);
        assert_eq!(dir_index(1, -1), 7);
        assert_eq!(dir_index(0, 0), 0);
    }

    #[test]
    fn pitch_index_quantizes_five_levels() {
        let max = 20.0f32.to_radians();

        // Single level (flat) always maps to 0.
        assert_eq!(pitch_index(0.0, max, 1), 0);
        assert_eq!(pitch_index(max, max, 1), 0);

        // Five levels: 0 = nose-down, 2 = level, 4 = nose-up.
        assert_eq!(pitch_index(-max, max, 5), 0);
        assert_eq!(pitch_index(-10.0f32.to_radians(), max, 5), 1);
        assert_eq!(pitch_index(0.0, max, 5), 2);
        assert_eq!(pitch_index(10.0f32.to_radians(), max, 5), 3);
        assert_eq!(pitch_index(max, max, 5), 4);
        // Clamps outside the range.
        assert_eq!(pitch_index(-1.5, max, 5), 0);
        assert_eq!(pitch_index(1.5, max, 5), 4);
    }

    #[test]
    fn pitch_spring_overshoots_and_bobs() {
        let dt = 1.0 / 60.0;
        let target = 0.1;
        let (mut pitch, mut vel) = (0.0f32, 0.0f32);
        let mut max_pitch = 0.0f32;
        for _ in 0..600 {
            let (p, v) = step_spring(pitch, vel, target, dt);
            pitch = p;
            vel = v;
            max_pitch = max_pitch.max(pitch);
        }
        // Underdamped: the body overshoots the target before settling near it.
        assert!(max_pitch > target, "expected overshoot, max {max_pitch} vs target {target}");
        assert!((pitch - target).abs() < 0.01, "did not settle: {pitch}");

        // An airborne target (nose-down) drives the angle negative.
        let (mut pitch, mut vel) = (0.0f32, 0.0f32);
        for _ in 0..600 {
            let (p, v) = step_spring(pitch, vel, AIRBORNE_PITCH, dt);
            pitch = p;
            vel = v;
        }
        assert!(pitch < 0.0, "airborne should pitch nose-down, got {pitch}");

        // A zero (level) roll target settles to ~0.
        let (mut roll, mut vel) = (0.5f32, 0.0f32);
        for _ in 0..600 {
            let (r, v) = step_spring(roll, vel, 0.0, dt);
            roll = r;
            vel = v;
        }
        assert!(roll.abs() < 0.01, "roll should settle to level, got {roll}");
    }

    #[test]
    fn pitch_index_quantizes_three_roll_levels() {
        let max = 20.0f32.to_radians();
        // Three roll levels: 0 = right-up (left-down), 1 = level, 2 = left-up.
        assert_eq!(pitch_index(-max, max, 3), 0);
        assert_eq!(pitch_index(0.0, max, 3), 1);
        assert_eq!(pitch_index(max, max, 3), 2);
    }

    #[test]
    fn derived_offsets_round_trip_through_iso() {
        let cell = [247.0, 247.0];
        let tile_scale = 45.0;
        let body = [[0.5f32, 0.7352f32]; 8];
        // A synthetic front-left wheel anchor per direction; exact values don't
        // matter, only that the round-trip reproduces the anchor delta.
        let mut wheels = [[[0.5f32, 0.5f32]; 8]; 4];
        wheels[0][0] = [0.566155, 0.618458];
        wheels[1][0] = [0.73363, 0.702169];
        wheels[2][0] = [0.211113, 0.795979];
        wheels[3][0] = [0.378535, 0.879716];

        let offsets = derive_wheel_offsets(&body, &wheels, cell, tile_scale);

        for i in 0..4 {
            let delta = Vec3::new(
                (wheels[i][0][0] - body[0][0]) * cell[0],
                (wheels[i][0][1] - body[0][1]) * cell[1],
                0.0,
            );
            let iso = iso_to_cartesian_4().transform_point3(Vec3::new(
                tile_scale * offsets[i][0][0],
                tile_scale * offsets[i][0][1],
                0.0,
            ));
            assert!((iso.x - delta.x).abs() < 1e-3, "wheel {i} x {iso} vs {delta}");
            assert!((iso.y - delta.y).abs() < 1e-3, "wheel {i} y {iso} vs {delta}");
        }
    }

    #[test]
    fn spawn_vehicle_creates_body_and_wheels() {
        let mut engine = Engine::new_for_test();
        let tm = engine.world.spawn((test_tilemap(), Role::new(RoleKind::Tilemap)));
        engine.names.insert("tilemap".into(), tm);

        let def = VehicleDef {
            name: "lrv".into(),
            directions: 8,
            columns: 4,
            rows: 2,
            cell: [247.0, 247.0],
            pitch_levels: 1,
            pitch_max_deg: 20.0,
            roll_levels: 1,
            roll_max_deg: 20.0,
            path_footprint: Some(vec![(0, 0)]),
            safe_fall_px: 0.0,
            turn_rate_deg_per_sec: 720.0,
            parts: vec![
                serde_json::from_value(serde_json::json!({
                    "name": "body", "texture": "lrvBody",
                    "anchors": [[0.5, 0.7352], [0.5, 0.7352], [0.5, 0.7352], [0.5, 0.7352],
                                [0.5, 0.7352], [0.5, 0.7352], [0.5, 0.7352], [0.5, 0.7352]]
                }))
                .unwrap(),
                serde_json::from_value(serde_json::json!({
                    "name": "wheel_fl", "texture": "lrvWheelFl",
                    "anchors": [[0.566, 0.618], [0.712, 0.676], [0.733, 0.768], [0.618, 0.841],
                                [0.434, 0.852], [0.288, 0.794], [0.267, 0.702], [0.382, 0.629]]
                }))
                .unwrap(),
                serde_json::from_value(serde_json::json!({
                    "name": "wheel_fr", "texture": "lrvWheelFr",
                    "anchors": [[0.734, 0.702], [0.712, 0.794], [0.566, 0.852], [0.382, 0.841],
                                [0.266, 0.768], [0.288, 0.676], [0.434, 0.618], [0.618, 0.629]]
                }))
                .unwrap(),
                serde_json::from_value(serde_json::json!({
                    "name": "wheel_rl", "texture": "lrvWheelRl",
                    "anchors": [[0.211, 0.796], [0.210, 0.676], [0.378, 0.591], [0.618, 0.590],
                                [0.789, 0.674], [0.790, 0.794], [0.622, 0.880], [0.382, 0.880]]
                }))
                .unwrap(),
                serde_json::from_value(serde_json::json!({
                    "name": "wheel_rr", "texture": "lrvWheelRr",
                    "anchors": [[0.379, 0.880], [0.210, 0.794], [0.211, 0.674], [0.382, 0.590],
                                [0.621, 0.591], [0.790, 0.676], [0.789, 0.796], [0.618, 0.880]]
                }))
                .unwrap(),
            ],
        };
        engine.vehicles.insert("lrv".into(), def);

        assert!(engine.spawn_vehicle("lrv", "lrv", 1.0, 1.0));
        assert!(engine.has_name("lrv"));
        for s in ["lrvWheelFl", "lrvWheelFr", "lrvWheelRl", "lrvWheelRr"] {
            assert!(engine.has_name(s), "missing {s}");
        }
        assert_eq!(engine.get_pos("lrv").map(|(x, y, _)| (x, y)), Some((1.0, 1.0)));

        let body = *engine.names.get("lrv").unwrap();
        {
            let veh = engine.world.get::<&IsoVehicle>(body).unwrap();
            assert_eq!(veh.wheel_entities[0], "lrvWheelFl");
            // Wheel offsets derived (non-zero for the front-left wheel at dir 0).
            assert!(veh.wheel_tile_offsets[0][0][0].abs() > 0.0);
            assert!(veh.wheel_tile_offsets[2][0][0].abs() > 0.0);
            assert!(veh.wheel_tile_offsets[0][0][0] != veh.wheel_tile_offsets[2][0][0]);
        }

        // goto/stop still work after spawn.
        let nav = NavMesh {
            position: Vec3::ZERO,
            scale: Vec3::ONE,
            map_entity: "tilemap".into(),
            tile_set: "navTileset".into(),
            data_grid: None,
            data: vec![1; 9],
            size_x: 3,
            size_y: 3,
        };
        let nm = engine.world.spawn((nav, Role::new(RoleKind::NavMesh)));
        engine.names.insert("navmesh".into(), nm);

        assert!(matches!(goto_sync(&mut engine, "lrv", 2, 1), VehicleGotoPoll::Accepted(_)));
        assert!(!engine.world.get::<&IsoVehicle>(body).unwrap().path.is_empty());
        assert!(engine.vehicle_stop("lrv"));
        assert!(engine.world.get::<&IsoVehicle>(body).unwrap().path.is_empty());
    }

    #[test]
    fn spawn_vehicle_sets_frame_name_when_table_exists() {
        let mut engine = Engine::new_for_test();
        let tm = engine.world.spawn((test_tilemap(), Role::new(RoleKind::Tilemap)));
        engine.names.insert("tilemap".into(), tm);
        engine.vehicles.insert("lrv".into(), lrv_def(720.0));

        // An empty frame table is enough: `frame_name` only keys off the
        // texture name, so the frame resolves to `{texture}_{frame}`.
        let empty = FrameTable { version: 1, sheets: vec![], frames: Default::default() };
        for texture in ["lrvBody", "lrvWheelFl", "lrvWheelFr", "lrvWheelRl", "lrvWheelRr"] {
            engine.frame_tables.insert(texture.into(), empty.clone());
        }

        assert!(engine.spawn_vehicle("lrv", "lrv", 1.0, 1.0));
        let body = *engine.names.get("lrv").unwrap();
        let wheel = *engine.names.get("lrvWheelFl").unwrap();

        // Initial pose (direction 0): body frame 0, wheel frame 0.
        let body_sprite = engine.world.get::<&IsoSprite>(body).unwrap();
        assert_eq!(body_sprite.frame_name.as_deref(), Some("lrvBody_0"));
        let wheel_sprite = engine.world.get::<&IsoSprite>(wheel).unwrap();
        assert_eq!(wheel_sprite.frame_name.as_deref(), Some("lrvWheelFl_0"));

        // Without a table, `frame_name` stays `None` (grid path takes over).
        let mut bare = Engine::new_for_test();
        let tm = bare.world.spawn((test_tilemap(), Role::new(RoleKind::Tilemap)));
        bare.names.insert("tilemap".into(), tm);
        bare.vehicles.insert("lrv".into(), lrv_def(720.0));
        assert!(bare.spawn_vehicle("lrv", "lrv", 1.0, 1.0));
        let bare_body = *bare.names.get("lrv").unwrap();
        assert_eq!(bare.world.get::<&IsoSprite>(bare_body).unwrap().frame_name, None);
    }

    #[test]
    fn spawn_vehicle_sizes_body_sheet_by_pitch_levels() {
        let mut engine = Engine::new_for_test();
        let tm = engine.world.spawn((test_tilemap(), Role::new(RoleKind::Tilemap)));
        engine.names.insert("tilemap".into(), tm);

        // Front wheels anchor to the +X side of the frame, rear wheels to -X,
        // and left/right wheels to distinct +Y/-Y, so both the front-rear
        // wheelbase and the left-right track are non-zero.
        let body = [[0.5, 0.5]];
        let fl = [[0.7, 0.4]];
        let fr = [[0.7, 0.6]];
        let rl = [[0.3, 0.4]];
        let rr = [[0.3, 0.6]];
        let def = VehicleDef {
            name: "lrv".into(),
            directions: 8,
            columns: 4,
            rows: 2,
            cell: [247.0, 247.0],
            pitch_levels: 3,
            pitch_max_deg: 20.0,
            roll_levels: 3,
            roll_max_deg: 20.0,
            path_footprint: Some(vec![(0, 0)]),
            safe_fall_px: 0.0,
            turn_rate_deg_per_sec: 720.0,
            parts: vec![
                serde_json::from_value(serde_json::json!({
                    "name": "body", "texture": "lrvBody", "anchors": body
                }))
                .unwrap(),
                serde_json::from_value(serde_json::json!({
                    "name": "wheel_fl", "texture": "lrvWheelFl", "anchors": fl
                }))
                .unwrap(),
                serde_json::from_value(serde_json::json!({
                    "name": "wheel_fr", "texture": "lrvWheelFr", "anchors": fr
                }))
                .unwrap(),
                serde_json::from_value(serde_json::json!({
                    "name": "wheel_rl", "texture": "lrvWheelRl", "anchors": rl
                }))
                .unwrap(),
                serde_json::from_value(serde_json::json!({
                    "name": "wheel_rr", "texture": "lrvWheelRr", "anchors": rr
                }))
                .unwrap(),
            ],
        };
        engine.vehicles.insert("lrv".into(), def);

        assert!(engine.spawn_vehicle("lrv", "lrv", 1.0, 1.0));
        let body_entity = *engine.names.get("lrv").unwrap();
        let wheel = *engine.names.get("lrvWheelFl").unwrap();

        let body_sprite = engine.world.get::<&IsoSprite>(body_entity).unwrap();
        let wheel_sprite = engine.world.get::<&IsoSprite>(wheel).unwrap();
        assert_eq!(body_sprite.tile_set_size, Vec2::new(4.0, 18.0));
        assert_eq!(wheel_sprite.tile_set_size, Vec2::new(4.0, 2.0));

        let veh = engine.world.get::<&IsoVehicle>(body_entity).unwrap();
        assert_eq!(veh.pitch_levels, 3);
        assert!((veh.pitch_max - 20.0f32.to_radians()).abs() < 1e-6);
        assert!(veh.wheelbase_px > 0.0);
        assert_eq!(veh.roll_levels, 3);
        assert!((veh.roll_max - 20.0f32.to_radians()).abs() < 1e-6);
        assert!(veh.track_px > 0.0);
    }

    #[test]
    fn goto_rejected_while_airborne() {
        let mut engine = Engine::new_for_test();
        let tm = engine.world.spawn((test_tilemap(), Role::new(RoleKind::Tilemap)));
        engine.names.insert("tilemap".into(), tm);
        let nav = NavMesh {
            position: Vec3::ZERO,
            scale: Vec3::ONE,
            map_entity: "tilemap".into(),
            tile_set: "navTileset".into(),
            data_grid: None,
            data: vec![1; 9],
            size_x: 3,
            size_y: 3,
        };
        let nm = engine.world.spawn((nav, Role::new(RoleKind::NavMesh)));
        engine.names.insert("navmesh".into(), nm);

        let def = VehicleDef {
            name: "lrv".into(),
            directions: 8,
            columns: 4,
            rows: 2,
            cell: [247.0, 247.0],
            pitch_levels: 1,
            pitch_max_deg: 20.0,
            roll_levels: 1,
            roll_max_deg: 20.0,
            path_footprint: Some(vec![(0, 0)]),
            safe_fall_px: 0.0,
            turn_rate_deg_per_sec: 720.0,
            parts: vec![
                serde_json::from_value(serde_json::json!({
                    "name": "body", "texture": "lrvBody",
                    "anchors": [[0.5, 0.7352], [0.5, 0.7352], [0.5, 0.7352], [0.5, 0.7352],
                                [0.5, 0.7352], [0.5, 0.7352], [0.5, 0.7352], [0.5, 0.7352]]
                }))
                .unwrap(),
                serde_json::from_value(serde_json::json!({
                    "name": "wheel_fl", "texture": "lrvWheelFl",
                    "anchors": [[0.566, 0.618], [0.712, 0.676], [0.733, 0.768], [0.618, 0.841],
                                [0.434, 0.852], [0.288, 0.794], [0.267, 0.702], [0.382, 0.629]]
                }))
                .unwrap(),
                serde_json::from_value(serde_json::json!({
                    "name": "wheel_fr", "texture": "lrvWheelFr",
                    "anchors": [[0.734, 0.702], [0.712, 0.794], [0.566, 0.852], [0.382, 0.841],
                                [0.266, 0.768], [0.288, 0.676], [0.434, 0.618], [0.618, 0.629]]
                }))
                .unwrap(),
                serde_json::from_value(serde_json::json!({
                    "name": "wheel_rl", "texture": "lrvWheelRl",
                    "anchors": [[0.211, 0.796], [0.210, 0.676], [0.378, 0.591], [0.618, 0.590],
                                [0.789, 0.674], [0.790, 0.794], [0.622, 0.880], [0.382, 0.880]]
                }))
                .unwrap(),
                serde_json::from_value(serde_json::json!({
                    "name": "wheel_rr", "texture": "lrvWheelRr",
                    "anchors": [[0.379, 0.880], [0.210, 0.794], [0.211, 0.674], [0.382, 0.590],
                                [0.621, 0.591], [0.790, 0.676], [0.789, 0.796], [0.618, 0.880]]
                }))
                .unwrap(),
            ],
        };
        engine.vehicles.insert("lrv".into(), def);

        assert!(engine.spawn_vehicle("lrv", "lrv", 1.0, 1.0));
        let body = *engine.names.get("lrv").unwrap();

        // Grounded: goto succeeds.
        assert!(matches!(goto_sync(&mut engine, "lrv", 2, 1), VehicleGotoPoll::Accepted(_)));
        assert!(!engine.world.get::<&IsoVehicle>(body).unwrap().path.is_empty());
        engine.vehicle_stop("lrv");

        // Airborne: goto is rejected and the path stays empty.
        engine.world.get::<&mut IsoVehicle>(body).unwrap().airborne = true;
        assert!(matches!(goto_sync(&mut engine, "lrv", 2, 1), VehicleGotoPoll::NoPath));
        assert!(engine.world.get::<&IsoVehicle>(body).unwrap().path.is_empty());
    }

    #[test]
    fn heading_and_dir_round_trip() {
        for d in 0..8u32 {
            assert_eq!(heading_to_dir(dir_to_heading(d)), d, "direction {d} round-trips");
        }
        // Negative and wrapped headings quantize to the expected frames.
        assert_eq!(heading_to_dir(-std::f32::consts::FRAC_PI_4), 7);
        assert_eq!(heading_to_dir(std::f32::consts::TAU), 0);
        assert_eq!(heading_to_dir(std::f32::consts::FRAC_PI_2), 2);
    }

    #[test]
    fn wrap_pi_bounds_angles() {
        assert!(wrap_pi(0.0).abs() < 1e-6);
        assert!((wrap_pi(0.5) - 0.5).abs() < 1e-6);
        assert!((wrap_pi(std::f32::consts::PI) - std::f32::consts::PI).abs() < 1e-4);
        assert!((wrap_pi(3.0 * std::f32::consts::PI) - std::f32::consts::PI).abs() < 1e-4);
        assert!((wrap_pi(-3.0 * std::f32::consts::PI) + std::f32::consts::PI).abs() < 1e-4);
    }

    #[test]
    fn lerp_dir2_interpolates_between_frames() {
        let vals = [
            [0.0, 0.0],
            [10.0, 0.0],
            [10.0, 10.0],
            [0.0, 10.0],
            [-10.0, 10.0],
            [-10.0, 0.0],
            [-10.0, -10.0],
            [0.0, -10.0],
        ];
        // Midway between East (0) and SouthEast (1) at heading π/8.
        let mid = lerp_dir2(&vals, std::f32::consts::FRAC_PI_8);
        assert!((mid[0] - 5.0).abs() < 1e-6 && mid[1].abs() < 1e-6);
        // Exactly at a frame reproduces that frame's values.
        let at_east = lerp_dir2(&vals, 0.0);
        assert_eq!(at_east, [0.0, 0.0]);
    }

    #[test]
    fn bounded_turn_steers_forward_only() {
        // Start heading East, waypoint due South — the vehicle must arc forward
        // (never reverse) and turn no faster than the configured rate.
        let mut heading = 0.0f32;
        let turn_rate = 45.0f32.to_radians();
        let dt = 1.0 / 60.0;
        let (tx, ty) = (1.5f32, 5.0f32);
        let (mut x, mut y) = (1.0f32, 1.0f32);
        let mut prev_heading = heading;

        for _ in 0..120 {
            let desired = (ty - y).atan2(tx - x);
            let err = wrap_pi(desired - heading);
            let max_turn = turn_rate * dt;
            let dh = err.clamp(-max_turn, max_turn);
            assert!(dh.abs() <= max_turn + 1e-6, "turn rate bounded");
            heading = wrap_pi(heading + dh);
            assert!(heading >= prev_heading - 1e-6, "no reverse — heading monotonic");
            prev_heading = heading;

            let step = 1.0 * dt;
            x += heading.cos() * step;
            y += heading.sin() * step;
        }

        assert!(
            (heading - std::f32::consts::FRAC_PI_2).abs() < 0.4,
            "heading should converge toward south: {heading}"
        );
    }

    /// Build a minimal LRV vehicle definition (body + 4 wheels, flat anchors)
    /// with a configurable turn rate for movement tests.
    fn lrv_def(turn_rate_deg: f32) -> VehicleDef {
        let part = |name: &str, texture: &str, anchors: [f32; 2]| VehiclePartDef {
            name: name.into(),
            texture: texture.into(),
            anchors: vec![anchors],
        };
        VehicleDef {
            name: "lrv".into(),
            directions: 8,
            columns: 4,
            rows: 2,
            cell: [247.0, 247.0],
            pitch_levels: 1,
            pitch_max_deg: 20.0,
            roll_levels: 1,
            roll_max_deg: 20.0,
            path_footprint: None,
            safe_fall_px: 0.0,
            turn_rate_deg_per_sec: turn_rate_deg,
            parts: vec![
                part("body", "lrvBody", [0.5, 0.7352]),
                part("wheel_fl", "lrvWheelFl", [0.566, 0.618]),
                part("wheel_fr", "lrvWheelFr", [0.734, 0.702]),
                part("wheel_rl", "lrvWheelRl", [0.211, 0.796]),
                part("wheel_rr", "lrvWheelRr", [0.379, 0.880]),
            ],
        }
    }

    #[test]
    fn spawn_vehicle_auto_derives_footprint() {
        let mut engine = Engine::new_for_test();
        let tm = engine.world.spawn((test_tilemap(), Role::new(RoleKind::Tilemap)));
        engine.names.insert("tilemap".into(), tm);
        engine.vehicles.insert("lrv".into(), lrv_def(90.0));

        assert!(engine.spawn_vehicle("lrv", "lrv", 1.0, 1.0));
        let body = *engine.names.get("lrv").unwrap();
        let v = engine.world.get::<&IsoVehicle>(body).unwrap();

        // Auto-derived footprint is a full rectangle covering the wheel extent
        // plus a 1-tile margin.
        assert!(!v.path_footprint.is_empty());
        let half_x = v.path_footprint.iter().map(|p| p.0.abs()).max().unwrap();
        let half_y = v.path_footprint.iter().map(|p| p.1.abs()).max().unwrap();
        assert!(half_x >= 1 && half_y >= 1, "footprint should cover the wheel extent");
        assert_eq!(
            v.path_footprint.len() as i32,
            (half_x * 2 + 1) * (half_y * 2 + 1),
            "footprint must be a full rectangle"
        );
    }

    #[test]
    fn lookahead_targets_a_point_ahead() {
        // Straight east path, vehicle at (1, 1): with lookahead 2 the target
        // lands two tiles east of the vehicle on the first segment.
        let path = [[1, 1], [5, 1], [9, 1]];
        let (gx, gy, idx) = lookahead(&path, 1, 1.5, 1.5, 2.0);
        assert_eq!(idx, 1);
        assert!((gx - 3.5).abs() < 1e-4 && (gy - 1.5).abs() < 1e-4, "got ({gx}, {gy})");

        // A longer look-ahead crosses into the next segment and advances idx.
        let (gx, gy, idx) = lookahead(&path, 1, 1.5, 1.5, 6.0);
        assert_eq!(idx, 2);
        assert!((gx - 7.5).abs() < 1e-4 && (gy - 1.5).abs() < 1e-4, "got ({gx}, {gy})");

        // Exhausting the path returns the final waypoint center.
        let (gx, gy, idx) = lookahead(&path, 1, 1.5, 1.5, 100.0);
        assert_eq!(idx, path.len());
        assert!((gx - 9.5).abs() < 1e-4 && (gy - 1.5).abs() < 1e-4, "got ({gx}, {gy})");
    }

    #[test]
    fn lookahead_skips_a_passed_waypoint() {
        // Vehicle past the corner: path goes east then south, but the vehicle is
        // already east of the corner.  It must skip the corner waypoint rather
        // than target a point behind it.
        let path = [[1, 1], [5, 1], [5, 5]];
        let (gx, gy, idx) = lookahead(&path, 1, 5.5, 1.5, 2.0);
        // The corner (5,1) is behind the vehicle; look-ahead continues south.
        assert!(idx >= 2, "corner waypoint should be skipped, got idx {idx}");
        assert!((gx - 5.5).abs() < 1e-4 && gy > 1.5, "got ({gx}, {gy})");
    }

    #[test]
    fn pure_pursuit_reaches_goal_without_orbiting() {
        let mut engine = Engine::new_for_test();
        let size = 20i32;
        let tm_e = engine.world.spawn((flat_tilemap(size, size), Role::new(RoleKind::Tilemap)));
        engine.names.insert("tilemap".into(), tm_e);
        engine.vehicles.insert("lrv".into(), lrv_def(90.0));

        assert!(engine.spawn_vehicle("lrv", "lrv", 1.0, 1.0));
        let body = *engine.names.get("lrv").unwrap();

        // L-shaped path with a 90-degree corner: (1,1) -> (5,1) -> (5,5).
        {
            let mut v = engine.world.get::<&mut IsoVehicle>(body).unwrap();
            v.path = vec![[1, 1], [5, 1], [5, 5]];
            v.path_idx = 1;
        }

        let mut last_idx = 0usize;
        let mut reached = false;
        for _ in 0..600 {
            engine.time.delta = 1.0 / 60.0;
            engine.update_vehicles();
            let v = engine.world.get::<&IsoVehicle>(body).unwrap();
            if v.path.is_empty() {
                reached = true;
                break;
            }
            assert!(v.path_idx >= last_idx, "path_idx went backwards");
            last_idx = v.path_idx;
        }
        assert!(reached, "vehicle never reached the goal after 600 frames");

        let (gx, gy, _) = engine.get_pos("lrv").unwrap();
        assert!(
            (gx - 5.5).abs() < 0.01 && (gy - 5.5).abs() < 0.01,
            "not snapped to goal: ({gx}, {gy})"
        );
    }

    /// A rectangular footprint `[-hx..=hx] × [-hy..=hy]`.
    fn rect_footprint(hx: i32, hy: i32) -> Vec<(i32, i32)> {
        let mut fp = Vec::new();
        for dy in -hy..=hy {
            for dx in -hx..=hx {
                fp.push((dx, dy));
            }
        }
        fp
    }

    /// The real LRV sidecar anchors (8 directions per part) from `lrv.json`.
    fn lrv_def_real() -> VehicleDef {
        let part = |name: &str, texture: &str, anchors: Vec<[f32; 2]>| VehiclePartDef {
            name: name.into(),
            texture: texture.into(),
            anchors,
        };
        VehicleDef {
            name: "lrv".into(),
            directions: 8,
            columns: 4,
            rows: 2,
            cell: [331.0, 331.0],
            pitch_levels: 5,
            pitch_max_deg: 20.0,
            roll_levels: 3,
            roll_max_deg: 20.0,
            path_footprint: None,
            turn_rate_deg_per_sec: 90.0,
            safe_fall_px: 96.0,
            parts: vec![
                part("body", "lrvBody", vec![[0.5, 0.6618]; 8]),
                part(
                    "wheel_fl",
                    "lrvWheelFl",
                    vec![
                        [0.549373, 0.574673],
                        [0.658127, 0.617648],
                        [0.674253, 0.686486],
                        [0.588304, 0.740864],
                        [0.450627, 0.748927],
                        [0.341873, 0.705952],
                        [0.325747, 0.637114],
                        [0.411696, 0.582736],
                    ],
                ),
                part(
                    "wheel_fr",
                    "lrvWheelFr",
                    vec![
                        [0.674361, 0.637148],
                        [0.658154, 0.706015],
                        [0.549303, 0.74898],
                        [0.411571, 0.740877],
                        [0.325639, 0.686452],
                        [0.341846, 0.617585],
                        [0.450697, 0.57462],
                        [0.588429, 0.582723],
                    ],
                ),
                part(
                    "wheel_rl",
                    "lrvWheelRl",
                    vec![
                        [0.284399, 0.70716],
                        [0.283399, 0.617648],
                        [0.40928, 0.554],
                        [0.588304, 0.553499],
                        [0.715601, 0.61644],
                        [0.716601, 0.705952],
                        [0.59072, 0.7696],
                        [0.411696, 0.770101],
                    ],
                ),
                part(
                    "wheel_rr",
                    "lrvWheelRr",
                    vec![
                        [0.409349, 0.769654],
                        [0.283371, 0.706014],
                        [0.284292, 0.616474],
                        [0.411571, 0.553486],
                        [0.590651, 0.553946],
                        [0.716629, 0.617586],
                        [0.715708, 0.707126],
                        [0.588429, 0.770114],
                    ],
                ),
            ],
        }
    }

    /// Build an engine with a 48×48 tilemap + all-walkable nav (the lrvtest
    /// shape), spawn a vehicle with a 7×5 footprint + safe_fall, and assert a
    /// flat click-to-move finds a path.
    fn engine_with_lrvtest_like_map(heights: Option<Vec<f32>>) -> Engine {
        let mut engine = Engine::new_for_test();
        let size = 48;
        let mut tm = flat_tilemap(size, size);
        tm.height_scale = 32.0; // matches commit_terrain(32.0) in lrv-guest
        if let Some(h) = heights {
            tm.height_data = h;
        }
        let tm_e = engine.world.spawn((tm, Role::new(RoleKind::Tilemap)));
        engine.names.insert("tilemap".into(), tm_e);

        let nav = NavMesh {
            position: Vec3::ZERO,
            scale: Vec3::ONE,
            map_entity: "tilemap".into(),
            tile_set: "navTileset".into(),
            data_grid: None,
            data: vec![1; (size * size) as usize],
            size_x: size,
            size_y: size,
        };
        let nm = engine.world.spawn((nav, Role::new(RoleKind::NavMesh)));
        engine.names.insert("navmesh".into(), nm);

        let mut def = lrv_def(90.0);
        def.path_footprint = Some(rect_footprint(3, 2)); // 7x5, matches auto-derive
        def.safe_fall_px = 96.0;
        engine.vehicles.insert("lrv".into(), def);

        engine
    }

    #[test]
    fn vehicle_goto_paths_across_flat_lrvtest_like_map() {
        let mut engine = engine_with_lrvtest_like_map(None);
        assert!(engine.spawn_vehicle("lrv", "lrv", 5.0, 5.0));
        assert!(
            matches!(goto_sync(&mut engine, "lrv", 24, 24), VehicleGotoPoll::Accepted(_)),
            "flat click-to-move should path"
        );
        let body = *engine.names.get("lrv").unwrap();
        assert!(!engine.world.get::<&IsoVehicle>(body).unwrap().path.is_empty());
    }

    #[test]
    fn vehicle_goto_paths_around_features() {
        // A gentle ramp band (0.375 units/tile) and a steep curb (1.0 unit/tile)
        // like the lrvtest map: the flat base and ramp faces must stay reachable.
        let size = 48;
        let n = (size + 1) as usize;
        let mut heights = vec![1.0f32; n * n];
        // East ramp: x in 33..=41, y in 20..=29, rise 3 units over 8 tiles.
        for y in 20..=29 {
            for x in 33..=41 {
                heights[y * n + x] = heights[y * n + x].max(1.0 + 3.0 * (x - 33) as f32 / 8.0);
            }
        }
        // Curb: x in 20..=36, y in 42..=47, +1 unit.
        for x in 20..=36 {
            for y in 42..=47 {
                heights[y * n + x] = heights[y * n + x].max(2.0);
            }
        }

        let mut engine = engine_with_lrvtest_like_map(Some(heights));
        assert!(engine.spawn_vehicle("lrv", "lrv", 5.0, 5.0));
        // Flat destination far from features.
        assert!(
            matches!(goto_sync(&mut engine, "lrv", 10, 10), VehicleGotoPoll::Accepted(_)),
            "flat destination should path"
        );
        // Ramp face (gentle) should be reachable.
        assert!(
            matches!(goto_sync(&mut engine, "lrv", 33, 25), VehicleGotoPoll::Accepted(_)),
            "gentle ramp face should path"
        );
    }

    #[test]
    fn real_lrv_def_auto_derives_and_paths() {
        let mut engine = engine_with_lrvtest_like_map(None);
        engine.vehicles.insert("lrv".into(), lrv_def_real());

        assert!(engine.spawn_vehicle("lrv", "lrv", 5.0, 5.0));
        let body = *engine.names.get("lrv").unwrap();
        let (half_x, half_y) = {
            let v = engine.world.get::<&IsoVehicle>(body).unwrap();
            let half_x = v.path_footprint.iter().map(|p| p.0.abs()).max().unwrap();
            let half_y = v.path_footprint.iter().map(|p| p.1.abs()).max().unwrap();
            (half_x, half_y)
        };
        let footprint_len = {
            let v = engine.world.get::<&IsoVehicle>(body).unwrap();
            v.path_footprint.len() as i32
        };
        assert_eq!(footprint_len, (half_x * 2 + 1) * (half_y * 2 + 1));

        assert!(
            matches!(goto_sync(&mut engine, "lrv", 24, 24), VehicleGotoPoll::Accepted(_)),
            "goto with real def + auto footprint"
        );
    }

    /// The full `lrvtest` ramp-course height field, mirroring
    /// `gen_lrvtest_map` in classic-roms: base 1.0, a central hill, four
    /// cardinal + four diagonal ramps, and a raised curb.
    fn lrvtest_heights() -> Vec<f32> {
        let size = 48usize;
        let n = size + 1;
        let mut h = vec![1.0f32; n * n];
        let idx = |x: usize, y: usize| y * n + x;

        // Central hill: +2 peak at (24,24), radius 5.
        for y in 0..n {
            for x in 0..n {
                let dx = x as f32 - 24.0;
                let dy = y as f32 - 24.0;
                let d = (dx * dx + dy * dy).sqrt();
                if d < 5.0 {
                    let bump = 2.0 * (1.0 - d / 5.0);
                    h[idx(x, y)] = h[idx(x, y)].max(1.0 + bump);
                }
            }
        }
        // Cardinal ramps.
        for y in 20..=29 {
            for x in 33..=41 {
                h[idx(x, y)] = h[idx(x, y)].max(1.0 + 3.0 * (x - 33) as f32 / 8.0);
            }
            for x in 7..=15 {
                h[idx(x, y)] = h[idx(x, y)].max(1.0 + 3.0 * (15 - x) as f32 / 8.0);
            }
        }
        for x in 20..=29 {
            for y in 33..=41 {
                h[idx(x, y)] = h[idx(x, y)].max(1.0 + 3.0 * (y - 33) as f32 / 8.0);
            }
            for y in 7..=15 {
                h[idx(x, y)] = h[idx(x, y)].max(1.0 + 3.0 * (15 - y) as f32 / 8.0);
            }
        }
        // Diagonal ramps.
        for x in 33..=41 {
            for y in 33..=41 {
                h[idx(x, y)] = h[idx(x, y)].max(1.0 + 3.0 * ((x + y) as f32 - 66.0) / 16.0);
            }
            for y in 7..=15 {
                h[idx(x, y)] =
                    h[idx(x, y)].max(1.0 + 3.0 * (x as f32 + (15.0 - y as f32) - 40.0) / 16.0);
            }
        }
        for x in 7..=15 {
            for y in 7..=15 {
                h[idx(x, y)] = h[idx(x, y)].max(1.0 + 3.0 * (30.0 - (x + y) as f32) / 16.0);
            }
            for y in 33..=41 {
                h[idx(x, y)] =
                    h[idx(x, y)].max(1.0 + 3.0 * (15.0 - x as f32 + y as f32 - 40.0) / 16.0);
            }
        }
        // Curb.
        for x in 20..=36 {
            for y in 42..=47 {
                h[idx(x, y)] = h[idx(x, y)].max(2.0);
            }
        }
        h
    }

    #[test]
    fn vehicle_goto_paths_on_full_lrvtest_map() {
        let mut engine = engine_with_lrvtest_like_map(Some(lrvtest_heights()));
        engine.vehicles.insert("lrv".into(), lrv_def_real());

        assert!(engine.spawn_vehicle("lrv", "lrv", 5.0, 5.0));

        // Flat base, the ramp faces (gentle slopes), and the central hill must
        // be reachable.
        assert!(
            matches!(goto_sync(&mut engine, "lrv", 20, 20), VehicleGotoPoll::Accepted(_)),
            "flat base should path"
        );
        assert!(
            matches!(goto_sync(&mut engine, "lrv", 11, 25), VehicleGotoPoll::Accepted(_)),
            "west ramp face should path"
        );
        assert!(
            matches!(goto_sync(&mut engine, "lrv", 33, 25), VehicleGotoPoll::Accepted(_)),
            "east ramp face should path"
        );
        assert!(
            matches!(goto_sync(&mut engine, "lrv", 24, 24), VehicleGotoPoll::Accepted(_)),
            "central hill should path"
        );
        assert!(
            matches!(goto_sync(&mut engine, "lrv", 16, 29), VehicleGotoPoll::Accepted(_)),
            "flat tile beside the ramp should path"
        );
        assert!(
            matches!(goto_sync(&mut engine, "lrv", 10, 10), VehicleGotoPoll::Accepted(_)),
            "nw diagonal ramp face should path"
        );
        // The 1-unit curb is a ~14.5° pitch over the wheelbase — within the
        // 20° limit, so the vehicle can drive over it.
        assert!(
            matches!(goto_sync(&mut engine, "lrv", 28, 45), VehicleGotoPoll::Accepted(_)),
            "1-unit curb should be traversable"
        );

        // The ramp's 3-unit cliff sides are a ~38° pitch over the wheelbase —
        // beyond the 20° limit, so the vehicle can't stand on them.
        assert!(
            matches!(goto_sync(&mut engine, "lrv", 7, 29), VehicleGotoPoll::NoPath),
            "ramp cliff edge should not path"
        );
    }
}
